### ISSUE TITLE
Model-view architecture with Plotitems

### ISSUE THREAD

**Issue by jcornford** [pyqtgraph/pyqtgraph#1013]
Hi, I opened a question on stack overflow (
https://stackoverflow.com/questions/57395786/how-to-use-a-model-view-architecture-with-pyqtgraph-plotting ) that I've copied in below. Sorry if you want to keep more general questions not in the issues, please feel free to close this if so. And apologies in advance if I've missed something obvious in how to code up what i'm asking! 

Is it possible to implement a model-view architecture with pyqtgraph? It seems like pyqtgraph forces you along a widget-centric approach (https://doc.qt.io/qt-5/modelview.html) in which each plotitem has its own scene? 

It would be great if the ViewBox (see image below from docs -http://www.pyqtgraph.org/documentation/plotting.html) would be an actual "view" of a scene, and the axis items around it would be dependent on that particular view. Therefore, if a number of PlotWidgets/PlotItems were displaying the same PlotDataItems at different zoom-levels, if you changed the zorder or scaled an item this would be shown on all the PlotItems without resorting to sending signals etc between PlotItems. 

To do this does the ViewBox have to be an embedded GraphicsView? Or is it possible to have a PlotItem on multiple GraphicsViews?

Thanks!

**Comment by j9ac9k** [comment]
@jcornford  pyqtgraph definitely takes a widget centric approach, but there is no reason you can't create your own wrappers for pyqtgraph objects/viewboxes that give them the relevant hooks.  

In my usage of pyqtgraph, I generally treat pyqtgraph objects as views (and initialize them in the my view code).  i generally have a `PlotView` object and a `PlotController` object (no reason you can't have a `PlotModel` if you wanted to), and I interact with different parts of the pyqtgraph modules as I see fit.

That said, I don't think there would be much motivation to introduce a second API that conforms to MVC architecture due to the limited number of developer hours we have as is.

I doubt this was a satisfying answer, but hopefully you can get some progress.  If you do decide this would be interesting to implement, I would encourage you to create a library that uses pyqtgraph as a dependency and creates a layer such that hooks are accessible appropriately.
