### ISSUE TITLE
Cannot import RawImageGLWidget

### ISSUE THREAD

**Issue by museee** [pyqtgraph/pyqtgraph#104]
Running the example code on my Ubuntu 14.04 computer (running Anaconda 2.1.0) I cannot get any Image-based examples to run. The error is always something like the one pasted in below. I've tried both the latest release 0.98, and a clone from the latest source. I'd appreciate any help that you can provide.

Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
  File "VideoTemplate_pyqt.py", line 220, in <module>
    from pyqtgraph.widgets.RawImageWidget import RawImageGLWidget, RawImageWidget
ImportError: cannot import name RawImageGLWidget

**Comment by spstromberg** [comment]
Hello, I had the same problem. Had to install PyOpenGL and PyOpenGL-accelerate and this resolved. 

I'm assuming since there were checks to make sure openGL was there and I must have passed them, that I actually needed to update those packages not install them (though I didn't check if they existed first). Might need to check version numbers on the import.

**Comment by j9ac9k** [comment]
Closing as it's a fairly stale issue and it appears that optional dependencies weren't met.
