### ISSUE TITLE
Incompatibility with Python 3.8 on Windows

### ISSUE THREAD

**Issue by jpgill86** [pyqtgraph/pyqtgraph#1077]
As has been summarized [here](https://github.com/conda-forge/pyqtgraph-feedstock/issues/10), pyqtgraph 0.10.0 is broken in Python 3.8, for Windows only. The issue was fixed in #980, but this hasn't been released yet. If there aren't plans to create a new release in the near future, would it be possible to get a backport of that fix, released as 0.10.1 (or 0.10.0.1)?

**Comment by j9ac9k** [comment]
Hi @jpgill86 

Thanks for the report.  Current stable release being incompatible with python 3.8 is a known issue (hence the accepted pull request you referenced).  We're getting close to a release, you can see our project progress here: https://github.com/pyqtgraph/pyqtgraph/projects/1  We don't have a release date ready.

One particular hold up has been getting consistent CI results on macOS involving some of the openGL examples, which been a constant thorn in the side.  @2xB has had a crack at this in PR #982 if you have some experience in this area, we could certainly use help.

For the time being our advice is to install pyqtgraph via pip directly from our git repo here:

```
pip install git+https://github.com/pyqtgraph/pyqtgraph@develop
```

Alternatively if you're using a `requirements.txt` file you can add an entry such as this:

```
git+https://github.com/pyqtgraph/pyqtgraph.git@684882455773f410e07c0dd16977e5696edaf6ce#egg=pyqtgraph
```

I know this isn't ideal, and if you'd like to review/comment on some of the outstanding PRs, or create PRs for issues in the project, we would certainly appreciate the help.

As this specific issue has already been fixed in the `develop` branch, I'm going to close this issue.

**Comment by jpgill86** [comment]
Thanks for the background, @j9ac9k! I wasn't aware of the project page.

I'm a Windows user, so unfortunately I don't already have experience that I could apply to the particular Mac issue you described. However, when I have some more time I'll poke around the project page in search of ways I can contribute.

Requiring a development version of pyqtgraph for [my cross-platform app](https://github.com/jpgill86/neurotic) is certainly not ideal, especially since you tell me it's broken! 😖 I think that backporting #980 would be a rather simple solution for all pyqtgraph users that aren't using the dev version but want to start using Python 3.8. The process is fairly straightforward:

1. Create a maintenance branch called "``0.10.x``" at tag ``pyqtgraph-0.10.0``
2. Cherry-pick the necessary commits containing compatibility fixes and commit them to the branch
3. Create a new release with version number 0.10.0.1 or 0.10.1 from the maintenance branch

If someone with write privileges was willing to first create the branch, I'd be happy to open the pull request containing the fixes. After merging, someone with permissions would then have to perform the release.

I recognize this is a hassle, but I hope you will reconsider it. 😊

**Comment by ksunden** [comment]
We have now released 0.11.0rc0 to [pypi](https://pypi.org/project/pyqtgraph/0.11.0rc0/).

**Comment by jpgill86** [comment]
> 
> 
> We have now released 0.11.0rc0 to [pypi](https://pypi.org/project/pyqtgraph/0.11.0rc0/).

Exciting! When I have more time I'll give it a try!

**Comment by AlphonsGwatimba** [comment]
> > We have now released 0.11.0rc0 to [pypi](https://pypi.org/project/pyqtgraph/0.11.0rc0/).
> 
> Exciting! When I have more time I'll give it a try!

Thanks for this!

**Comment by stonebig** [comment]
may we get an 0.11.0rc1 soon ?

**Comment by j9ac9k** [comment]
We may do another release, is there a specific fix you need in your library that is not incorporated in rc0?
