### ISSUE TITLE
How to lock aspect ratio to 1?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [pyqtgraph/pyqtgraph#1143]
`setLimits` disables zooming beyond the limits set, and `setAspectLocked` doesn't seem to do anything. How can I fix x & y limits to obey a given aspect ratio (e.g. both -5 to 5 --> 1 ratio), without zoom constraint?

<hr>

**Context**: modified [`p6`](https://github.com/pyqtgraph/pyqtgraph/blob/develop/examples/Plotting.py#L58)

```python
pg.setConfigOptions(antialias=True, background='w', foreground='k')
app = QtGui.QApplication([])
win = pg.GraphicsWindow()
win.resize(1000, 600)

p6 = win.addPlot(title="Updating plot")
p6.showGrid(x=True, y=True)
curve = p6.scatterPlot(pen='b', size=3)
x = np.random.randn(100, 1000)
y = np.random.randn(*x.shape) * 4

ptr = 0
def update():
    global curve, data, ptr, p6
    curve.setData(x=x[ptr % len(x)], y=y[ptr % len(y)])
    if ptr == 0:
        p6.enableAutoRange('xy', False)
    ptr += 1
timer = QtCore.QTimer()
timer.timeout.connect(update)
timer.start(50)

if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
    QtGui.QApplication.instance().exec_()
win.close()
```

**Comment by ixjlyons** [comment]
I'm not sure exactly what you're after. `setAspectLocked` with a ratio 1 ensures x and y spacing are equal on your screen regardless of zoom or viewbox dimensions. If you resize the window, you should see the grid remain square with `setAspectLocked(True)`.

If you want the X and Y range to be linked so the range is always the same, something like this kinda works, but it's an odd effect:

```python
import pyqtgraph as pg
import numpy as np

app = pg.mkQApp()

x = np.random.randn(1000)
y = np.random.randn(*x.shape) * 4

p = pg.plot()
p.showGrid(x=True, y=True)
curve = p.scatterPlot(x, y, pen='b', size=3)
p.setXRange(-5, 5)
p.sigXRangeChanged.connect(lambda _, t: p.setYRange(*t))

app.exec_()
```

Maybe that with constrained translation of the axes so you always zoom to/from the center?

**Comment by OverLordGoldDragon** [comment]
@ixjlyons That's exactly it, almost; I have to zoom in/out at least once for it to take effect. Can this step be skipped (or automated programmatically)? Also your code's nicer in that Python doesn't crash after closing the window.

<details>
  <summary>Updated animation</summary>

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore
import numpy as np

pg.setConfigOptions(antialias=True, background='w', foreground='k')

app = pg.mkQApp()

x = np.random.randn(100, 1000)
y = np.random.randn(*x.shape) * 4

p = pg.plot()
p.showGrid(x=True, y=True)
curve = p.scatterPlot(pen='b', size=3)
p.setXRange(-5, 5)
p.sigXRangeChanged.connect(lambda _, t: p.setYRange(*t))

ptr = 0
def update():
    global curve, data, ptr, p
    curve.setData(x=x[ptr % len(x)], y=y[ptr % len(y)])
    if ptr == 0:
        p.enableAutoRange('xy', False)
    ptr += 1
timer = QtCore.QTimer()
timer.timeout.connect(update)
timer.start(50)

app.exec_()
```
</details>

**Comment by ixjlyons** [comment]
> I have to zoom in/out at least once for it to take effect. Can this step be skipped (or automated programmatically)?

Ahh yep, I should've noticed that. If you move the `p.setXRange(-5, 5)` line after connecting the `sigXRangeChanged` signal, setting the initial range will trigger setting the y range as well.

> Python doesn't crash after closing the window

I'm guessing that was just from having `win.close()` after the `QApplication` exits.

Going to close this as answered. Feel free to re-open or make another issue if you come across other problems.

**Comment by OverLordGoldDragon** [comment]
@ixjlyons Thank you. Also, `win.close()` actually enables 1 rerun before crash - without it, the crash occurs upon the very first closure.

**Comment by OverLordGoldDragon** [comment]
@ixjlyons A problem; I'm only able to pan diagonally - [demo](https://puu.sh/FlQxb/fa5335aa29.mp4). Should I open a new issue?

**Comment by ixjlyons** [comment]
That's why I mentioned it's sort of an odd effect for an interactive visualization -- it's a consequence of linking the x and y ranges together. Panning is effectively just shifting both the min and max range of an axis. Free 2D panning allows the shift amount (and direction) of each of the axes to be independent, but since the y range is forced to be the same as the x range in this example, you've removed a degree of freedom such that panning is constrained to be along the line y = x. If you want the shape of the scatterplot blob to be maintained at any zoom/window size, `setAspectLocked` should do that (if it doesn't, we should re-open the issue). If you ask for both (i.e. add `p.setAspectLocked(True)` in the example above), there's an infinite recursion because it's impossible to satisfy both conditions for a viewbox of arbitrary display dimensions. If you want the plot itself to maintain a fixed aspect ratio (so there's empty space on the sides or top/bottom in a rectangular window), you'd need to specify that constraint at the `PlotWidget` level I think.

**Comment by OverLordGoldDragon** [comment]
@ixjlyons Er... `setAspectLocked` works perfectly now. Don't know what the problem was before - but your approach does differ from one in my original post from the examples (e.g. it doesn't use `mkQApp`). Anyway, all's good - thanks again.
