### ISSUE TITLE
flowchart Error "Cyclic dependency detected"

### ISSUE THREAD

**Issue by hzyrc6011** [pyqtgraph/pyqtgraph#1195]
I tried to make a control system simulation with pg flowchart. However it comes out with this error. Control systems need feedbacks,which is necessary.
Maybe there's error in my  code. How can I avoid this error? Thanks!

**Comment by 2xB** [comment]
Can you share a minimal working example that leads to this error? For example you could copy your current code and successively delete as much as possible until you are left with a few lines of code that reproduce the error.

Also, it would be great if you would fill out the default issue template (the template you see when clicking on "New issue" and then on "Get started"), as that massively helps tracking down what your problem might be.

**Comment by j9ac9k** [comment]
Hi,

I'm sorry but there is not enough information for us to attempt to reproduce the error.  Please follow the template for new issues as it helps us better identify potential issues.

**Comment by ixjlyons** [comment]
The `flowchart` module only supports acyclic (feedforward) networks. The documentation mentions this limitation: https://pyqtgraph.readthedocs.io/en/latest/flowchart/index.html

You can always implement feedback programmatically. Say you have nodes A, B, and C and you want a feedback connection from C back to B:

```
[A] --> [B] --> [C] -.
         ^           |
         '-----------'
```

In C's `process` method, you can directly set an attribute (or call some callback) of B so that next time the flowchart is run through, B's process method will get the input from A and will already have the previous output of C.
