### ISSUE TITLE
Runtime Error in mouseMoveEvent - can not be traced back to call in application

### ISSUE THREAD

**Issue by Knusper** [pyqtgraph/pyqtgraph#1213]
### Short description

My application using pyqtgraph crashes, and I don't even know why, as all I see on the console after a crash is:
```
Traceback (most recent call last):
  File "/home/ehere/miniconda3/envs/astroconda/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 162, in mouseMoveEvent
    self.sendHoverEvents(ev)
  File "/home/ehere/miniconda3/envs/astroconda/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 228, in sendHoverEvents
    items = self.itemsNearEvent(event, hoverable=True)
  File "/home/ehere/miniconda3/envs/astroconda/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 426, in itemsNearEvent
    shape = item.shape() # Note: default shape() returns boundingRect()
RuntimeError: wrapped C/C++ object of type LinearRegionItem has been deleted
```

### Expected behavior

No Runtime Error.  Traceback that could be linked in to call in application.

### Tested environment(s)

 * PyQtGraph version: 0.10.0
 * Qt Python binding:  ??
 * Python version:  3.6.10
 * Operating system:  Linux
 * Installation method:  conda - from anaconda channel

**Comment by 2xB** [comment]
Could you please quickly provide three things:
1. Does the error still occur, when you install pyqtgraph version 0.11.0rc0 from pip?
2. Could you please copy the application you are programming and successively simplify and delete everything that is not strictly needed to reproduce this error, until you are left with a very short minimal working example of code that you can post here? Such an example that one can execute on one's own computer is very important and massively saves time.
3. The output of
```python3
import pyqtgraph
print(pyqtgraph.Qt.VERSION_INFO)
```

**Comment by ixjlyons** [comment]
Appears to be similar to #524. See also https://github.com/pyqtgraph/pyqtgraph/issues/80#issuecomment-49897776. Are you using `deleteLater` by chance?

**Comment by Knusper** [comment]
> Could you please just provide three further things:
> 
> 1. Does the error still occur, when you install pyqtgraph version 0.11.0rc0 from pip?
> 2. Could you please copy the application you are programming and successively simplify and delete everything that is not strictly needed to reproduce this error, until you are left with a very short minimal working example of code that you can post here? Such an example that one can execute on one's own computer is very important and massively saves time.
> 3. The output of
> 
> ```python
> import pyqtgraph
> print(pyqtgraph.Qt.VERSION_INFO)
> ```

1.  I will try soon.
2.  This appears very difficult, as the code is several thousand lines of code.  So I don't even know where to start. Right now the error occurs randomly, i.e. I can not even reproduce what interaction  leads to the crash.
3. 'PyQt5 5.9.2 Qt 5.9.6'

> Appears to be similar to #524. See also [#80 (comment)](https://github.com/pyqtgraph/pyqtgraph/issues/80#issuecomment-49897776). Are you using `deleteLater` by chance?

No.

**Comment by 2xB** [comment]
Okay, thank you! For 2, don't worry, it's usually looking very hard at first, but deleting large amounts of stuff turns out to go very fast. It's also a great excercise, since one sometimes accidentally learns which parts of a codebase interact with which other parts, and if one is experienced in isolating a bug by deleting everything else, that is quite a useful skill for tracking down bugs in general, especially when one has no idea where a bug might come from.

Also, when deleting code, you don't have to care about not breaking features, since in the minimal working example in the end you don't want those features anyways. Just care about not breaking the bug.

Deleting is quite intuitive once one gets started, but here is a guide anyways:
#### A more cookbook-like guide
After deleting something, run the application, ensure that the bug still occurs, delete more.
It might help to start with looking if entire Python files can be deleted (and the corresponding `import <pythonfilename>`), often enough that creates errors in functions that are not executed when testing this bug anyways. 
If some classes are not strictly needed, delete them.
Afterwards you might want to delete as much as possible in the remaining files, beginning from the bottom, deleting entire functions and code that calls these functions - again, you don't care if you break anything that is independent of your bug anyways.

**Comment by 2xB** [comment]
The bug btw. probably occurs after you do something with your GUI (e.g. switching visible plot widget?), maybe wait a second or two and then hovering above a `LinearRegionItem`? This kind of bug means usually that somewhere Qt is convinced that it lost all references to an object and therefore deletes it (see also https://wiki.qt.io/PySide_Pitfalls ). Without example code, it is hard to judge what is responsible for this though, since neither our testing suite and nor testing examples by hand gave us this exact error so far.

**Comment by Knusper** [comment]
This bug appears very infrequent, that is the problem... Its not something, that I start the application and after 5 seconds or so it crashes... Some input (which I haven't figured out) may trigger it... Probably I should be looking for things triggered by mouse movement?

**Comment by 2xB** [comment]
That was a lucky shot, the answer I sent one minute before you asked the question actually faces that exact question ^^

**Comment by 2xB** [comment]
It might also be that in your application a `LinearRegionItem` (the thing that highlights or selects an x or y axis range) is only sometimes visible or is under some circumstance deleted and the error might occur when you actively move your mouse pointer over the `LinearRegionItem` while it is destroyed.

**Comment by j9ac9k** [comment]
I suspect first order of business should be to try the 0.11rc0 I think some bugs in this area should be sorted out....but would definitely like to know if this is not the case!

**Comment by Knusper** [comment]
I will try with the rc0 first, thanks!

**Comment by Knusper** [comment]
OK - so I tried with 0.11rc0 (`0.11.0.dev0+g0e62913`) and I ran the application for almost a day without the crash - so I guess this has been fixed.

**Comment by j9ac9k** [comment]
I'm really glad to hear it.  I'm going to close out this issue, but if you still run into some issues, please open a new issue.  Hopefully we'll have 0.11 shipped sooner than later.
