### ISSUE TITLE
No easy way to override the `ViewBox` passed to a `PlotItem`

### ISSUE THREAD

**Issue by goodboy** [pyqtgraph/pyqtgraph#1259]
[`PlotItem` currently allows passing in a `viewBox` argument](https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L138) and it appears to expect an *instance* but in the `viewBox=None` case, it instantiates a new `ViewBox with:
```python
viewBox = ViewBox(parent=self)
```
This is problematic since usually you would want the `ViewBox` **you pass in** to have the `.parent` reference to the `PlotItem` in order to ensure correct downstream functionality?

So, we have a causality dilemma when trying to create a `PlotItem` with a **custom** `ViewBox` that should also have reference to it's parent `PlotItem` (why might you want this - see #1258).

#### Proposal
- Add a `ViewBox.add_viewbox()` method which takes in a `ViewBox` instance or subtype.
- Call this method on `viewBox` in `__init__()` if `viewBox is not None`.
- Support some elegant way to give the custom `ViewBox` a reference to it's parent `PlotItem`.
   - with the additional method added this step would likely have to be done by the user: :
   ```python
   vb = CustomViewBox()
   pi = PlotItem(viewBox=vb)
   vb.parent = pi
   ```

I have a patch for this already if there is interest in a PR.

**Comment by goodboy** [comment]
Oh and following up on making the `ViewBox` adding *lazy* (done after instantiation) we'll need to be aware that [`PlotItem.setAxisItems()`](https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L289) is called from `__init__()` which does [axis linking using the `.vb`](https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L332).

To work around this we might have to loop through `self.axes` to re-link for any new `ViewBox` passed to `.add_viewbox()`.

**Comment by 2xB** [comment]
**First the good news:**
There is no need for a `ViewBox` to have a `PlotItem` as a `parent`. You can execute the last code snippet that you posted and it already just works. An example is given in `examples/customPlot.py`, where a custom `ViewBox` is instantiated and used as argument `viewBox` for `pg.PlotWidget`, where it is passed to the constructor of `pg.PlotItem`, in exactly the way you propose.

**So why did you observe this `parent=self`:**
For Qt commonly `parent=self` is used to avoid early *garbage collection*/to help with memory management. If you create your own `ViewBox`, you are responsible for storing references on your own to avoid garbage collection, so you don't need to pass specifically a `PlotItem` as `parent` there. If you construct the `ViewBox` to later use it with the PlotItem in an other widget, you can pass that widget as `parent`. Or you pass nothing, does also work. But be aware that everything that does not have a parent needs to be at least stored in some variable, otherwise it might be deleted too early.
You can find more about `parent`s and memory management in Qt here: https://doc.qt.io/qt-5/objecttrees.html

**Comment by 2xB** [comment]
Btw. I think you can also do this:
```python3
vb = CustomViewBox()
pi = PlotItem(viewBox=vb)
vb.setParent(pi)
```

**Comment by goodboy** [comment]
@2xB hehe that sounds a lot easier then what I've somehow convinced myself of :smiley: 

Let me try this and see if it'll indeed work.

>If you create your own ViewBox, you are responsible for storing references on your own to avoid garbage collection, so you don't need to pass specifically a PlotItem as parent there. 

Yeah I find this whole convention really odd. If you want components to have access to one another it seems to me a flat namespace is a lot easier. I guess I didn't grow up in the era of inheritance :eyes:

**Comment by j9ac9k** [comment]
The way of setting the parent is definitely calling `setParent(child)` and not `child.parent = parent` (actually, do we even keep track of a `.parent` attribute, if so, why?)

I'm not sure I'm seeing a benefit here, with the current mechanisms, we can instantiate PlotItems or ViewBox's in any order, and still setup the Qt parent hierarchy.

Lastly I just want to put it out there that pyqtgraph has quite a bit of code for Qt child/parent management, and generally speaking, users shouldn't need to be setting those explicitly.

**Comment by j9ac9k** [comment]
> Yeah I find this whole convention really odd. If you want components to have access to one another it seems to me a flat namespace is a lot easier. I guess I didn't grow up in the era of inheritance 👀

This is due to Qt's handling of objects, that we inherited (heh).  Given the tight coupling to Qt that pyqtgraph has, we try and follow their conventions wherever feasible

**Comment by 2xB** [comment]
@goodboy Well inheritance/object oriented programming is a huge thing to get used to after experience in other paradigms :D So let's quickly talk about this convention, adding to @j9ac9k's remarks. More can be found in https://doc.qt.io/qt-5/objecttrees.html . Note that if this is solved for you, you can close this issue,

First it's important to know that `parent`s are not about having access. They are about how things are deleted. Issue being: If an object - let's call it A - is deleted that is part of another object - call it B - (e.g. a widget A in an other widget B), B doesn't know necessarily about A being deleted. So B could still try to access A, e.g. when trying to draw A. That's an issue, since trying to access a deleted object can result in whatever, e.g. a segmentation fault.
So how to solve this issue? Qt solves this by the so-called object trees: Object A stores a reference to B as its "parent", and when A is deleted, it tells B that it no longer exists. So B will no longer try to access A, exactly as it should. 

@j9ac9k If I get this correctly, `.parent` is an invention by @goodboy since they weren't aware of `setParent`.

**Comment by goodboy** [comment]
@2xB sweet, thanks for that link, I understand now that it's for purposes of teardown and avoiding *draw on null* type errors. Maybe that's why *subconsciously* I was concerned about making sure the parent was set right :wink:.

Also, yes, if `addParent()` solves this then I will for sure close this issue.

**Comment by j9ac9k** [comment]
@goodboy I would only call the `.setParent()` methods as a last resort... as I said in an earlier post, there is a fair amount of code in pyqtgraph to sort out the parent hierarchy correctly for you.

First, I would attempt @2xB 's solution of just instantiating in this order:

```python
vb = CustomViewBox()
pi = PlotItem(viewBox=vb)
```

Let us know how it goes.

**Comment by goodboy** [comment]
@j9ac9k @2xB yup seems to have worked just fine.

I must have gotten confused at some point ensuring the parent was set.
Thanks for all the explanations and superb help :tropical_drink:
