### ISSUE TITLE
No signal coming out from PlotDataItem sigClicked

### ISSUE THREAD

**Issue by paulgoulain** [pyqtgraph/pyqtgraph#1315]
Hi,

I tried to play with signals emitted by PlotDataItem, especially the sigClicked but I don't understand why nothing seems to be triggered. Here a minimal code :

```
from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
import sys

class Window(QtGui.QMainWindow):

    def __init__(self):
        
        super().__init__()

        self.plot_window = pg.PlotWidget(self)
        curve = pg.PlotDataItem([0, 1, 10], [0, 1, 10])
        curve.sigClicked.connect(self.print_test)
        self.plot_window.addItem(curve)

        layout = QtGui.QHBoxLayout()
        layout.addWidget(self.plot_window)

        w = QtGui.QWidget()
        w.setLayout(layout)
        self.setCentralWidget(w)

    def print_test(self):
        print('clicked')

 if __name__ == "__main__":

    app = QtGui.QApplication(sys.argv)

    win = Window()
    win.setWindowTitle('PyzyPlot')
    win.show()
    sys.exit(app.exec())
```

When the PlotDataItem is clicked, I expect to see 'clicked' printed in the console, but nothing happend. Am I doing something wrong ?

Paul

**Comment by pijyoi** [comment]
add the following line
```python
curve.curve.setClickable(True)
```

**Comment by paulgoulain** [comment]
Hi,

Thanks for your answer, it works ! But the way to enable this signal is kind of shady . It is written nowhere in the documentation that it is mandatory to make the item clickable.

Anyway, I close this issue.

Paul

**Comment by ixjlyons** [comment]
@paulgoulain fair point - this needs to be obvious in the `PlotDataItem` documentation given it's intended to be the object users typically instantiate/interact with (rather than `PlotCurveItem` and `ScatterPlotItem` directly). I'm going to re-open and suggest we add more to the `PlotDataItem.sigClicked` description mentioning a `PlotDataItem` with only a curve won't emit unless the underlying curve item is set to be clickable.

Alternatively, we could automatically set the curve to be clickable when there is no scatter plot here https://github.com/pyqtgraph/pyqtgraph/blob/d70e870a44e47144f6511730854eb980039f7c13/pyqtgraph/graphicsItems/PlotDataItem.py#L529

That's probably not a great idea though because I could imagine explicitly *not* wanting the curve to be clickable so it doesn't steal click events you do want to receive elsewhere.

**Comment by pijyoi** [comment]
PlotDataItem constructor now supports a "clickable" keyword since https://github.com/pyqtgraph/pyqtgraph/pull/1714

**Comment by j9ac9k** [comment]
Thanks @pijyoi for updating this issue, I think we can close this out now.
