### ISSUE TITLE
Idea/Enhancement - Possibility to add a scale bar to pyqtgraph's 3D Graphics System

### ISSUE THREAD

**Issue by Cocco17** [pyqtgraph/pyqtgraph#1354]
I am using pyqtgraph to visualize sensor data from autonomous cars. In the future I would like to add a scale bar to the visualization to help the user figuring out distances to objects etc. 

I found the scale bar example that is coming along with pyqtgraph; however it is only meant for the 2D plotting system.

Does anybody already tried to implement a scale bar for the 3D System? 

Thanks a lot in advance!

**Comment by vitsensei** [comment]
I have used pyqtgraph's 3D modules for quite a bit in the past. I have to tell you, if you have something more complicated, more "animated" going, it performs quite poorly. The reason is pyqtgraph, in my understanding, is using OpenGL's fixed pipeline, which is no longer used in most modern applications.

**Comment by Cocco17** [comment]
@vitsensei any other recommendation? What would be state-of-the-art to use in my Qt-Application? 

I already had my problems with pyqtgraph. It’s quite hard to integrate a 3D Model of the Ego Car for example..

**Comment by vitsensei** [comment]
@Cocco17 Give Vispy a go. If you want more control over how you render your car model, you might want to learn OpenGL (the modern approach). That being said, the OpenGL Bible book is probably 1000+ pages. Since you are asking this question, I think I can safely assume that you are not a graphic engineer, which probably means learning OpenGL will be a rocky road for you.

**Comment by Cocco17** [comment]
@vitsensei you guessed correctly :P I'd love to avoid the need to look deeper into OpenGL and all that stuff.. 

During my research I also stumbled over ModernGL (https://github.com/moderngl/moderngl) - is that the modern approach you meant?

PS: Thanks a lot for your support btw!

**Comment by vitsensei** [comment]
@Cocco17 ModernGL definitely makes your life easier, but you won't get far without going through the actual theory of OpenGL, which is quite something.

**Comment by Cocco17** [comment]
@vitsensei then I guess I'll give Vispy a shot :) Big thumbs up, appreciate your time and help!

**Comment by j9ac9k** [comment]
I'm going to close out this issue, but yeah, our (pyqtgraph maintainers) position is that `vispy` has more stable/higher performance/more capable 3D capabilities than pyqtgraph.
