### ISSUE TITLE
Feature - Add Available Colors

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#1407]
PyQtGraph currently has only minimal numbers of colormaps or specified colors baked in the library, that functionality really should expand

Bokeh for example offers an extensive list of palettes and colors (some of which are sources from CSS named colors, some are sourced from [brewer](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3):

https://docs.bokeh.org/en/latest/docs/reference/palettes.html
https://docs.bokeh.org/en/latest/docs/reference/colors.html

In addition, we should consider adding the colors from the following sources

-  QML [QtQuick.Controls.Material](https://doc.qt.io/qt-5/qtquickcontrols2-material.html)
- [Complete 2014 Material Design Color Listing](https://material.io/design/color/the-color-system.html#tools-for-picking-colors)
- [iOS System Colors](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/)
- [Microsoft Colors](https://docs.microsoft.com/en-us/uwp/api/windows.ui.colors?view=winrt-19041)
- [CSS Color Names](https://www.w3schools.com/colors/colors_groups.asp)
- [Color Brewer](https://colorbrewer2.org/#)
- [SVG Color Keywords](https://www.w3.org/TR/SVG11/types.html#ColorKeywords)

Now, how do we organize all these colors/colormaps?

**Comment by ntjess** [comment]
How would you feel about `matplotlib` colormaps as well? My application currently has this dependency due to the lack of cyclical colormaps natively available in `pyqtgraph`. I know there is a list in `GradientEditorItem`, but these are hard to use for regular LUTs unless you are explicitly creating a `GradientEditorItem`.

E.g. a `maptlotlib` style colormap where you can call `cmap([3,4,5])` and get a 3x4 array of RGBA colors.

Would this request fall under the same issue? Thanks for considering.

**Comment by j9ac9k** [comment]
Adding mpl colormaps would totally fall under this umbrella! Only thing I'm not sure about is how to organise the colors, and how to make them accessible via API.

Bokeh would likely be the best example here, that or matplotlib itself.

**Comment by NilsNemitz** [comment]
I would also like to see a convenient way to handle custom color palettes and perceptually uniform color maps in pyqtgraph.
For discussion, I have created some proof-of-concept code in PR #1424.

Since the major challenge to such an extension would seem to be efficient interaction with the colormapping code in ImageView, my idea is to simply include some extended functionality in the -known working- ColorMap object itself. ColorMap already stores an arbitrary list of color data. Only tiny extensions are needed to add optional names to the stored colors and to provide a usable shorthand syntax for accessing them.

Using pre-made colormaps or re-usable palettes then only needs a slightly more convenient way to load these from files on user request.

If the concept seems reasonable, I am hoping for suggestions for the actual implementation.

**Comment by j9ac9k** [comment]
Wow, thanks for the PR! It totally made my day.  Thank you for tackling
this!

I'm going to hold off on commenting until I can sit down and give it the
due attention.

**Comment by 2xB** [comment]
There also exists `cmapToColormap` by @honkomonk, a matplotlib colormap converter with an example at the bottom: https://github.com/honkomonk/pyqtgraph_sandbox/blob/master/mpl_cmaps_in_ImageItem.py . They commented on this here: https://github.com/pyqtgraph/pyqtgraph/pull/1273#issuecomment-649528537

**Comment by NilsNemitz** [comment]
Dear @2xB , I have extended pull request #1424 to allow importing color maps from Matplotlib and Colorcet. I looked at @honkomonk 's MIT licensed code to write the Matplotlib importer.

After some discussion with @j9ac9k , I stripped out the support for named colors. That should probably be handled separately.

**Comment by j9ac9k** [comment]
Right now mkColor does accept fallback to the SVG color names, which is good enough for me.  Anyway I'm going to close this issue out as it addressed what I had intended.
