### ISSUE TITLE
www.pyqtgraph.org is down

### ISSUE THREAD

**Issue by StSav012** [pyqtgraph/pyqtgraph#1485]
[www.pyqtgraph.org](http://www.pyqtgraph.org/) is down. The connection times out.

**Comment by j9ac9k** [comment]
Some time ago we migrated out documentation to readthedocs, it can be accessible: https://pyqtgraph.readthedocs.io/en/latest/

I'm not sure if pyqtgraph.org is down due to an outage or if it was intentionally brought down; but the plan was to migrate to readthedocs.  That said, we should probably remove the link from `README.md`

**Comment by j9ac9k** [comment]
BTW website appears to be back up 👍
