### ISSUE TITLE
Regression in scrollingPlots example

### ISSUE THREAD

**Issue by ixjlyons** [pyqtgraph/pyqtgraph#1494]
### Short description

Plot `p3` in `examples/scrollingPlots.py` isn't working correctly as of #1391 (identified via bisect, #1413 doesn't fix it).

### Code to reproduce

```
$ python examples/scrollingPlots.py
```

### Expected behavior

The left plot on the second row (`p3`) should scroll to the left with continuously updated data, similarly to the plot on the bottom row.

### Real behavior

The plot continues to scroll but stops displaying data in the array beyond about 20 samples. Mouse interaction suddenly brings the hidden data into view. Screenshot after about 80 updates below - the left plot on the second row should have a curve extending all the way to x = 0:

![Screenshot_2021-01-09_08-19-29](https://user-images.githubusercontent.com/943602/104102863-e6a0e780-5253-11eb-8b7d-75497b185567.png)

### Tested environment(s)

 * PyQtGraph version:  386dcf81
 * Qt Python binding:  PyQt5 5.15.2, PySide2 5.15.2
 * Python version: 3.9.1
 * NumPy version:  1.19.5
 * Operating system: Linux
 * Installation method:  pip

**Comment by j9ac9k** [comment]
I can replicate this on the current master branch.

**Comment by jjuod** [comment]
Yeah, one more of my cache bugs... This time it is `setPos` which didn't invalidate the `viewRect` cache.
in fact, since `setPos` is not reimplemented in `PlotDataItem`, calling it did not trigger any of the pyqtgraph-specific signals, which I suspect might be a problem in some rare cases. For example, the clipping mask is updated on range changes, but not by `setPos` (added a PR with more details). Therefore I think it's worth doing that fix anyway.

Other than that, if you want to rollback the cache change in #1391, I fully understand - or I can just move the caching out to the ROI class, so that it's less likely to cause further mess. It also seems like the view cache is overall not that necessary after #1493.

**Comment by j9ac9k** [comment]
@jjuod I'm good w/ whatever you think is best; we all use the library and want it to work right, have maintainable code, and be fast; so our interests are in alignment.
