### ISSUE TITLE
https-version of http://www.pyqtgraph.org/

### ISSUE THREAD

**Issue by gituser789** [pyqtgraph/pyqtgraph#1514]
Is it possible to provide a https version for http://www.pyqtgraph.org/ e.g. by using https://letsencrypt.org/ including an automated forwarding to https-version?

**Comment by j9ac9k** [comment]
@campagnola who maintains the website has had his hands full in recent months.  That said, we really should have a https certificate there.  I'll leave this issue open, next time I hear from him, I'll nag him about this.

**Comment by 2xB** [comment]
Since quite some time, it was planned to make a new website and host it on GitHub Pages. That would also fix the certificate issue. At the time that was discussed, I created a website currently served under https://2xB.github.io for that purpose. If that would be a desired solution to this issue, the following would currently be left to do in https://github.com/2xB/2xb.github.io and this repository (PRs welcome):
 * move all further information from the current website to the pyqtgraph documentation
 * commit to either update the `News` section on the new page manually or to write a JS widget to fetch that information from GitHub
 * maybe improve CSS/theme
 * maybe add more meta tags for search engine optimization
 * remove the robots.txt that currently prevents it from being indexed on search engines

**Comment by j9ac9k** [comment]
Hey @2xB I didn't know you had worked on this.  Web related stuff is a real black hole to me, so I'm likely the last person that should drive any kind of effort here; but I'll gladly assist where possible.  How would you feel about migrating the site to the `pyqtgraph` group; so we can pull it up via `https://pyqtgraph.github.io`?

**Comment by 2xB** [comment]
@j9ac9k Yes, we can do that! That might also bring in others to do PRs for the site. Should we await the judging of a more web design oriented person, or move it directly?

**Comment by j9ac9k** [comment]
I don't have strong opinions on now vs. later; if you think you can bring in other people to do PRs, then you are likely in a far better place to determine _when_ the transition should happen.

**Comment by 2xB** [comment]
My pyqtgraph site example moved to https://2xb.github.io/pyqtgraph-website/ , with its GitHub repo at https://github.com/2xB/pyqtgraph-website . I'm currently not taking responsibility for maintaining it or solving its issues in the near future, but would definitely welcome if someone wants to e.g. fork it!

**Comment by j9ac9k** [comment]
Hey @2xB good to hear from you.

We have migrated to pyqtgraph.github.io and set the repo here: https://github.com/pyqtgraph/pyqtgraph.github.io

Unfortunately we still don't have a valid https cert tho :(

**Comment by 2xB** [comment]
Hey @j9ac9k, thank you! Currently I am not doing interactive visualization in Python that much, but it's always great to see how the development progresses here!

The https issue lies - to my understanding - in the DNS configuration of the pyqtgraph.com domain. Basically, steps 5 and onwards have to be done as described in https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site .

Also compare https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#https-errors .

**Comment by ixjlyons** [comment]
IMO we could just work on the front page of the docs and point the domain there https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-support

#1753 and examples gallery/ies (working on it) would help migrate I think

**Comment by j9ac9k** [comment]
This is working now, I'm going to close this issue

@ixjlyons I think we should indeed discuss the pyqtgraph.org homepage, and what it should be effectively; maybe a good time to discuss that is when galleries/examples and #1753 are introduced/merged?
