### ISSUE TITLE
PlotWidget text is covered if a border is added

### ISSUE THREAD

**Issue by tj-murphy** [pyqtgraph/pyqtgraph#1592]
### Short description
I'm building a GUI where I want to insert PlotWidgets. I think they would look nice with a border around the edges. I found that setStyleSheet can be used to do this. However, when I try to add a border, the text on my plot gets cut off.

### Code to reproduce
```
import sys

from PyQt5 import QtWidgets
from pyqtgraph.Qt import QtGui
import pyqtgraph as pg
import numpy as np

app = QtWidgets.QApplication(sys.argv)
mw = QtGui.QMainWindow()
w = pg.PlotWidget(mw)
w.setGeometry(50,50, 300, 300)
w.plot(y=np.random.normal(size=100))
w.setLabel('bottom',"My X-Axis Label")
#w.setStyleSheet("border:2px solid red")
mw.setFixedSize(400,400)
mw.show()

if __name__ == "__main__":
    QtGui.QApplication.instance().exec_()
```

### Expected behavior
The PlotWidget should recognize that the border is occupying space and that the space at the bottom is no longer available to put the text into. It should shrink the plotting area to be able to bump the X label upward so the label is unobscured by the border.

### Real behavior
If you uncomment the style sheet line above, you'll see that the X label is in the same place and is now being covered up by the border line. 

### Tested environment(s)

 * PyQtGraph version: `0.11.0rc0`
 * Qt Python binding: `PyQt5 5.14.1 Qt 5.12.8`
 * Python version: `3.8.5`
 * NumPy version: `1.20.1`
 * Operating system:  Ubuntu 20.04.2
 * Installation method: pip

### Additional context
I'm very new to pyqtgraph, so maybe the style sheet isn't the right way to add the border like I'm trying to do. If there's a more suitable alternative I'd love to be made aware of it. Alternatively if there's a way to tell pyqtgraph to build a margin around itself, so I can have the border live in that margin, that would be a very acceptable workaround.

**Comment by j9ac9k** [comment]
This isn't a pyqtgraph issue, you'll have this same problem with any QWidget, an easy way of doing this, is modifying the content margins, so that you have enough room around the contents such that the border doesn't overlap.

http://doc.qt.io/qt-5/qwidget.html#setContentsMargins <- you can do it this way...

if you're looking to have pyqtgraph manage borders though, you probably want to use a `pg.GraphicsLayoutWidget`, which uses a `GraphicsLayout` on the inside, and you can call the `setBorder` method of that:

https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/graphicslayout.html#pyqtgraph.GraphicsLayout.setBorder with whatever color/width you want.

I modified your example a little bit to draw both the layout border and apply the style sheet

![image](https://user-images.githubusercontent.com/646398/108546120-88791280-729d-11eb-9008-763657a3cac7.png)


```python
import sys

from PyQt5 import QtWidgets
from pyqtgraph.Qt import QtGui
import pyqtgraph as pg
import numpy as np

app = QtWidgets.QApplication(sys.argv)
mw = QtGui.QMainWindow()
w = pg.GraphicsLayoutWidget(mw)
w.ci.setBorder()  # modify this to specify color/width of border for the layout
w.setGeometry(50,50, 300, 300)
plot = w.addPlot(labels={'bottom': 'My X-Axis Label'}, y=np.random.normal(size=100))
w.setStyleSheet("border:2px solid red")
mw.setFixedSize(400,400)
mw.show()

if __name__ == "__main__":
    QtGui.QApplication.instance().exec_()
```

As I don't think this is a pyqtgraph issue, I'm going to close this out.  Thanks for opening the issue, as I discovered an API inconsistency in pyqtgraph, which I'll now go on to create an issue for.
