### ISSUE TITLE
Autoscale - Performance Regression

### ISSUE THREAD

**Issue by dgoeries** [pyqtgraph/pyqtgraph#1602]
### Short description
Between PyQtGraph 0.11.0 and further versions there is a **performance regression** noticeable for plots with **autoscale activated**. The older version is significantly faster.

Analysis of regression yields to PR !1435 

### Code to reproduce

Use the delivered PlotSpeedTest and activate autoscale by playing with the example.
```
https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/PlotSpeedTest.py
```

### Tested environment(s)

 * PyQtGraph version: master
 * Qt Python binding: 5.12.3
 * Python version: 3.8
 * NumPy version: any

**Comment by misantroop** [comment]
Similar performance degradation when setYRange without autoscale is called.

**Comment by j9ac9k** [comment]
@misantroop migrating the conversation here, instead of an already merged PR.

On my machine, the plot-speed test has rather minimal differences, definitely nothing in the 30-40% range.  While investigating this, we found another change between 0.11.0 and 0.11.1 that may have impacted performance (unfortunately for everyone involved, the other PR is necessary to fix an underlying Qt issue :| )

I think I've made some head-way in on my local machine, but as I'm not able to show significant performance differences, I'll have to have some others test to see how much performance is regained. I'll try and get a PR up later tonight.
