### ISSUE TITLE
Use funding to improve pyqtgraph

### ISSUE THREAD

**Issue by outofculture** [pyqtgraph/pyqtgraph#1620]
I'm seeking funding from [CZI](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/) to improve pyqtgraph, and I'd like to hear from others what parts of pyqtgraph are most in need of improvement, or are most easily addressed with monetary assistance. So far, ideas we have:

- GPU-equipped test runners
- dedicated benchmarking hardware
- improve `makeARGB` performance
  - the benchmarking hardware will make this easier
  - hiring a dedicated developer for this task
- tedious improvements like:
  - typing
  - architecture improvements
  - paying down tech debt
- outreach and community maintenance
  - documentation
  - hiring a developer to do bug squashing

What other ideas do people have?

( I'm hoping to hit as many active developers and users with this discussion as possible; it's also happening in slack, and I'll post to the mailing list. I'll try to keep this issue relatively in sync. )

**Comment by outofculture** [comment]
Tagging @pijyoi - can you think of ways to use money to speed up `makeARGB` in particular?

**Comment by j9ac9k** [comment]
I really want to hear from our users on this, so I'm going to tag some folks I know use this library, to solicit input from them, as I think our users should have a large say ... going off of memory here, so I'm sure I'm going to miss some people, but folks that come immediately to mind include:

@irgolic @markotoplak @pijyoi @hhslepicka @danielhrisca @NilsNemitz @ntjess @mliberty1

**Comment by outofculture** [comment]
Worth noting that we may not win funding with our proposal, but even if we don't, this discussion will be a nice synthesis of project goals.

**Comment by pijyoi** [comment]
>can you think of ways to use money to speed up makeARGB in particular?

QImage supports other formats than Format_ARGB32, so for those cases, having makeARGB() convert the data to ARGB format is a waste.
e.g. 
1) grayscale images --> Format_Grayscale8 (since Qt 5.5) or Format_Indexed8
2) RGB images --> Format_RGB888

For uses of LUT that is for colorization, those could perhaps be converted to using Format_Indexed8

**Comment by jpgill86** [comment]
Mentioning also @samuelgarcia 😄

**Comment by danielhrisca** [comment]
I'm only using a small part of pyqtgraph, but for my use case I would certainly like to see improved performance of 2D plots.

**Comment by j9ac9k** [comment]
> I'm only using a small part of pyqtgraph, but for my use case I would certainly like to see improved performance of 2D plots.

you mean like `ImageItem`s?

**Comment by danielhrisca** [comment]
> > I'm only using a small part of pyqtgraph, but for my use case I would certainly like to see improved performance of 2D plots.
> 
> you mean like `ImageItem`s?

I mean `PlotCurveItem` and `PlotDataItem`

**Comment by j9ac9k** [comment]
> > > I'm only using a small part of pyqtgraph, but for my use case I would certainly like to see improved performance of 2D plots.
> > 
> > 
> > you mean like `ImageItem`s?
> 
> I mean `PlotCurveItem` and `PlotDataItem`

Just for our own benchmarking purposes, can you give us an approximate size of the data arrays you're plotting?

**Comment by danielhrisca** [comment]
I use culling to display only the `min` and `max` values / pixel. The initial arrays can be up to millions of points.

I think the performance issue is also linked with the fact that each curve is handled by a dedicated ViewBox and all the ViewBox's are X-linked. In case of a large curve count the performance penalty is visible.

**Comment by j9ac9k** [comment]
> I use culling to display only the `min` and `max` values / pixel. The initial arrays can be up to millions of points.
> 
> I think the performance issue is also linked with the fact that each curve is handled by a dedicated ViewBox and all the ViewBox's are X-linked. In case of a large curve count the performance penalty is visible.

hey, wanted to chat w/ you about this very thing, but this is probably the wrong place.  Would you mind emailing me?  My email is in my github profile page.

**Comment by mliberty1** [comment]
First, thank you to all for supporting and maintaining this project!  Bridging the gap between Python, PySide & PyQt, and Qt requires a lot of patience and diligence.

I don't have any huge feature requests.  I do have some specifics:

1.  Issue [#1612](https://github.com/pyqtgraph/pyqtgraph/issues/1612), which could be very annoying.  [Joulescope](https://www.joulescope.com/) (my product, I use pyqtgraph for the host UI) has been successful, and I now have money to spend to address issues like this.  Does pyqtgraph have a bounty program or way to pay (like contracting a maintainer on Upwork) for investigations like this?

2. Similar to @danielhrisca, faster performance for FillBetweenItem would be nice.  I like the look of FillBetweenItem for displaying min/max behind mean:
![image](https://user-images.githubusercontent.com/5393422/110119722-326e9980-7d8a-11eb-8923-ef6dc5c059a7.png)
However, it really slows down the frame rate and reduces Qt responsiveness.   
The Joulescope UI data buffer defaults to 30 seconds (60,000,000 samples per signal, ~1 GB RAM across all signals), but I have some customers with lots of RAM that use 5 minutes (300,000,000 samples) or more.  Like @danielhrisca, I have a custom "view" that reduces it to pixels.  pyqtgraph still struggles to keep up with FillBetweenItem.  I just did a quick profile, and the code spends a lot of time (8.2% total, self-time) in [updatePath](https://github.com/pyqtgraph/pyqtgraph/blob/829f07b24ae0c3368ce463e43f3998a82f659457/pyqtgraph/graphicsItems/FillBetweenItem.py#L60), but most of the time is in the GraphicsView.paintEvent.
![image](https://user-images.githubusercontent.com/5393422/110123771-57194000-7d8f-11eb-9c7d-0e5d425e5dd2.png)
Drawing min & max as lines (no FillBetween) works great.

3. Improve performance for drawing curves thicker than 1 pixel.  As with FillBetweenItem, any larger pen sizes really slow down rendering.

4. A regular release cycle.  I think this has started (thanks @j9ac9k !), but perhaps funding could help. 

5. If you have the budget, I definitely agree with hiring someone to handle bugs and keep up with the unrelenting Python / Qt / PySide / PyQt march.

**Comment by jpgill86** [comment]
> Improve performance for drawing curves thicker than 1 pixel. As with FillBetweenItem, any larger pen sizes really slow down rendering.

+1 to this!

**Comment by irgolic** [comment]
Hey :)

Thanks for the ping, I mentioned this at our weekly core Orange developer meeting.

@markotoplak says:
> I am into performance improvement. What I would especially like is be able to draw multipixel-wide PlotCurveItems fast. I understand there is a Qt performance limitation in drawing anything over a single pixel wide, but it would be so good if you managed around this.

**Comment by jpgill86** [comment]
pyqtgraph does not utilize the GPU for rendering, right? Just CPU? Is GPU acceleration within the realm of possibility?

**Comment by danielhrisca** [comment]
Related to the general performance topic maybe it makes sense to have a C-extension module for accelerated functions that tackle the existing bottlenecks.

**Comment by j9ac9k** [comment]
> pyqtgraph does not utilize the GPU for rendering, right? Just CPU? Is GPU acceleration within the realm of possibility?

I'm sure other folks can likely have better explanations than I can, but pyqtgraph uses the GPU optionally in a handful of ways.

1. More recently, @outofculture added CuPy support to makeQImage.  For this to work, you must be using Windows/Linux and have a functional CUDA installation, as well as have cupy installed.
2. the 3D visualizations use OpenGL, this is not optional
3. the non-3D visualizations have an optional `useOpenGL` [config option](https://pyqtgraph.readthedocs.io/en/latest/config_options.html).  This has some potential side effects so care should be given.  

This is largely an area of the library that I do not interact with much.

Qt has a GPU framework abstraction layer for Metal, Vulkan, Direct3D, but it's only available for Qt Quick/QML but not available for QtWidgets and QGraphicsView so we won't be able to make use of it :(

**Comment by outofculture** [comment]
@j9ac9k beat me to it, of course. `useCupy` is the other config option.

Yes, expanding our use of the GPU is definitely possible and desired. The item above "GPU-equipped test runners" is an import ant part of that.

**Comment by j9ac9k** [comment]
> I am into performance improvement. What I would especially like is be able to draw multipixel-wide PlotCurveItems fast. I understand there is a Qt performance limitation in drawing anything over a single pixel wide, but it would be so good if you managed around this.

I remember seeing an old issue about this a while back, but I didn't realize this issue was so prevalent across projects.  No clue how feasible a fix is, or if this is purely an upstream issue with no workaround, but AFAIK we have not investigated it at all.  That's a wrong we'll right soon.

**Comment by ntjess** [comment]
Not sure how many people are interested in parameter tree improvements, but I think they've got a lot of potential. I'm currently using them in conjunction with a function doc parser to make arbitrary interactive python functions. I think it would be great to implement general functionality to coordinate with plots, settings, configs, etc.

With extra development work this could be tied more naturally to the flowchart API, too

**Comment by j9ac9k** [comment]
> Not sure how many people are interested in parameter tree improvements, but I think they've got a lot of potential. I'm currently using them in conjunction with a function doc parser to make arbitrary interactive python functions. I think it would be great to implement general functionality to coordinate with plots, settings, configs, etc.
> 
> With extra development work this could be tied more naturally to the flowchart API, too

Hi @ntjess while you are the first person to mention Parameter Tree's here, a number of outstanding pull requests revolve around them, and a number of issues, old and new relate to them too.  Given their use in the ScatterPlotSpeedTest.py benchmark, I do agree that they are an under-utilized feature, and they should get more support/attention.

**Comment by Tillsten** [comment]
We use pyqtgraph for our realtime lab-software. I also think that getting better performance with wider lines is crucial for modern screens, where 1px are much to narrow.

**Comment by j9ac9k** [comment]
@mliberty1 I knew from past issues/PRs that you had a tool that had some UI polish to it, but joulescope looks amazing!  Thanks for sharing, I figured that pyqtgraph would be a natural fit for some kind of electrical signal display; but hadn't actually seen it used in such a way.

> Does pyqtgraph have a bounty program or way to pay (like contracting a maintainer on Upwork) for investigations like this?

The idea here has _never_ crossed my mind.  I'm completely open to it, although I have no experience running such a program, so if you think getting something like that applied to pyqtgraph would be a good idea, would you mind creating a separate issue, because I really do think this is worthy of discussion!

> A regular release cycle. I think this has started (thanks @j9ac9k !), but perhaps funding could help.

This has been tedious/slow, and but it's only going to get better.  We've killed off Qt4 and <  Qt 5.12 support, we've adopted [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html) so iterating/developing is much easier than before.  Right now most development effort has been aimed at 

1. Performance regressions by recent changes
2. Bug fixes from recent regressions
3. Merging/Fixing existing PRs.  

The timing of this grant is fortunate as it comes at a time where I feel recent performance/bug regressions have largely been addressed (I know, some exceptions are out there) and existing PRs is < 30, and if I got aggressive w/ the merge button (and fixing my own PR) could likely be under 20.

> Related to the general performance topic maybe it makes sense to have a C-extension module for accelerated functions that tackle the existing bottlenecks.

@danielhrisca I'm not sure we're quite there yet, but I completely agree there are some functions that act as bottlenecks and work should be done to speed those up.  Right now I'm going to lean toward using numba for a few reasons

1. We can make `numba` an optional dependency, with minimal changes to our codebase
2. We can still ship "universal" wheels, the moment we ship cythonized anything, we'll have to make platform/python-specific versions, basically it would significantly complicate our packaging/release process.  For me to go onboard with this, I'm going to have to see some very compelling benchmarks vs. numba-ified methods.

If there are specific functions/methods whose performance is slowing things down, would you mind listing them here? https://github.com/pyqtgraph/pyqtgraph/issues/1253

**Comment by mliberty1** [comment]
Hi @j9ac9k - Thanks!  The Joulescope UI code is all Apache 2.0 open-source on [GitHub](https://github.com/jetperch/pyjoulescope_ui).   See the [waveform widget](https://github.com/jetperch/pyjoulescope_ui/tree/master/joulescope_ui/widgets/waveform) for the part using pyqtgraph.  Yes, pyqtgraph has been great for this project, and thank you for all your work on maintaining it!

I will open another issue regarding a bounty program or contracting options.

**Comment by titusjan** [comment]
Applying for funding is a great idea and thanks for tagging me in this discussion. 

In my opinion funding is a good opportunity to get some grunt work done. It's relatively easy to get volunteers to implement cool new features, but it's harder to find people to improve the documentation and getting rid of technical debt (although you are currently doing a great job). A paid programmer can help with this. I see that you guys already came to the same conclusion because you list it in the top post.

> Related to the general performance topic maybe it makes sense to have a C-extension module for accelerated functions that tackle the existing bottlenecks.

I really like the fact that PyQtGraph is pure python. This makes it easy to just fork it from Git and include the PyQt source in my project for debugging an making pull requests. Cython would make this more difficult. The Numa solution looks promising though.

About the performance: in my experience PyQtGraph can easily plot 100000 points but gets less and less snappy when you go above that. The one time I had to make a line plot of a milion points I had to resort to [Silx](http://www.silx.org/), which I don't like as much as PyQtGraph. Silx has an OpenGL backend, hence the speed. I understood the future of OpenGL is shaky, but perhaps this is something to consider implementing.

I know that PyQt has the `useOpenGL` global config option but I never could get it to work. The documentation even says "*Enable OpenGL in GraphicsView. This can have unpredictable effects on stability and performance.*." Does anybody use this option? I would say, either improve it or remove it.

Keep up the good work all.

**Comment by j9ac9k** [comment]
Hi @titusjan Thanks for your input!

There was one (good) point you made I wanted to address directly.

> I know that PyQt has the `useOpenGL` global config option but I never could get it to work. The documentation even says "Enable OpenGL in GraphicsView. This can have unpredictable effects on stability and performance.." Does anybody use this option? I would say, either improve it or remove it.

So this is actually an area of the library where as far as I know, no current maintainer or recent active contributor has much experience with (`openGL` that is) outside of using it within this library.   When that option was created, along with the warning, the state of openGL support within GraphicsViews is likely very different from what it is like today.  Earlier versions of Qt5 didn't even support openGL within the GraphicsView framework.  

This is a long-winded way of saying not only do we not have a good idea of what existing issues there are with openGL, but even if we did, we may not have anyone with the knowledge/skills in fixing the issues, issuing workarounds, or documenting what we can't fix upstream.

That said, I'm thinking we should get rid of that bit in the docs, we either support this, or we don't... and I'm all for supporting it.

**Comment by outofculture** [comment]
These ideas have been included in the proposal, and we can continue to reference this issue when determining priorities.
