### ISSUE TITLE
Remove reference to pyqtgraph-core repository from the documentation.

### ISSUE THREAD

**Issue by titusjan** [pyqtgraph/pyqtgraph#1624]
The [Embedding PyQtGraph as a sub-package of a larger project](https://pyqtgraph.readthedocs.io/en/latest/how_to_use.html#embedding-pyqtgraph-as-a-sub-package-of-a-larger-project) section of the documentation says that you can use the [pyqtgraph-core](https://github.com/pyqtgraph/pyqtgraph-core) repository as a sub tree in your project. However the pyqtgraph-core repository hasn't been updated in six years, The last commit is from May 2015.

I guess that this functionality is not used, so I think it's best to remove it from the documentation.

**Comment by j9ac9k** [comment]
Ha, actually that's something I've been low key working on restoring, but due to the size of the changes involved (due to moving files around and such), I decided to postpone fixing it until we get the outstanding PRs effectively squared away.  

I've also been trying to think about how it can be tested as well.

That support I see no harm on removing reference to it in the documentation and restoring it when we get `pyqtgraph-core` to actually sync up.

**Comment by j9ac9k** [comment]
After chatting w/ someone else who I know has used `pyqtgraph-core`, there seems to be no appetite to keep it any more, so I'm good w/ nuking it.  With that, I'll label this a good first issue.
