### ISSUE TITLE
ColorBarItem does not adapt to row-major setting

### ISSUE THREAD

**Issue by miketrumpis** [pyqtgraph/pyqtgraph#1733]
The new ColorBarItem class only sets up the color map gradient in column-major mode. This leads to a nearly blank ImageItem. See this description: https://groups.google.com/g/pyqtgraph/c/uhaELqEUoaI/m/TzYYUN0yAgAJ

A more simple MWE is to add "pg.setConfigOptions(imageAxisOrder='row-major')" to the existing ColorBarItem.py example script.

Here's the image creation, hard coded for column major:

https://github.com/pyqtgraph/pyqtgraph/blob/ec4d613037330d2dd59ff395f72052992a7e63e8/pyqtgraph/graphicsItems/ColorBarItem.py#L101-L108

I have a PR coming shortly.

**Comment by NilsNemitz** [comment]
Hi @miketrumpis,
It's exciting to see that we have users that dig into the new functions before I have even been able to make sure they are found in the documentation! Thank you for reporting this and for including a PR to fix it right away.

But can I ask you to have a quick look to check if the actual issue is still present in your use case?
We ran into the same (?) issue with #1720 , and hope that we fixed it in #1723 just a few days ago. There wasn't much discussion here since this was a pretty straightforward bug once discovered.

Our approach was to fix the axisOrder of the bar image to always be 'col-major':
`self.bar = ImageItem(axisOrder='col-major')`
Then no change to the shape of the data should be needed. This seemed sufficient on my system, for the test cases I managed to come up with.

If you still see this in a version of PyQtGraph from later than April 18, could you please let us know a little more about your environment / use case. Then we'll have another look!

**Comment by miketrumpis** [comment]
Oh no! I think I searched closed issues when I first encountered this, but not today when I discovered the bug. Yeah that's the same bug, and the present head of "master" (with the simpler fix) does solve this issue. 

I'm going to close this.

**Comment by NilsNemitz** [comment]
@miketrumpis , glad to hear that our stealthy bug fix already addressed this.

Please come back here with the next issues you find!
