### ISSUE TITLE
black box in lower left and lower right corners

### ISSUE THREAD

**Issue by RT-Tap** [pyqtgraph/pyqtgraph#1777]
Hi, So I am using pyqtgraph and trying to use a histogramLUTable inside of a viewbox to try and plot some data and I have this black box with a little A that is obstructing the graph origin/axis in the lower left hand corner and another blank box in the bottom right hand corner.  Upon asking on stackexchange i was informed I can use hideButtons() method however that only removes the A and not the black box.  It was suggested this is a bug.

Attached is a picture with the issues circled in red.
![pyprob4](https://user-images.githubusercontent.com/71105781/118379850-b96e9800-b5ab-11eb-8d20-3f19d136e537.jpg)

```
![pyprob4](https://user-images.githubusercontent.com/71105781/118379815-7c0a0a80-b5ab-11eb-9a60-5cf690104af8.jpg)
import PyQt5
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import pandas as pd
import pyqtgraph as pg

up = np.linspace(0,1,100)
down = np.flip(up)
nparray = np.hstack([up, down])
data = np.vstack([[nparray], [nparray],[nparray]])

app = QtGui.QApplication([]) 
win = pg.GraphicsLayoutWidget(show=True, title="pyqtGraph attempt", size=[800,600])  
view = pg.PlotItem() 
view.hideButtons()
win.addItem(view) #add the plotitem object to window widget
img = pg.ImageItem() #create Imageitem placeholder so we can add it to HistogramLUTable
view.addItem(img)
img.setImage(data)

if __name__ == '__main__':
    pg.mkQApp().exec_() #if this is the main window execute the creation of the window```

**Comment by NilsNemitz** [comment]
Hi @RT-Tap , sorry to hear that you are running trouble with the ImageItem.

At the moment I cannot seem to reproduce the problem. I am on the current master version, PyQt5 and Windows.
Here's what it looks like for me:
![black_box_bug](https://user-images.githubusercontent.com/19742018/118395172-dbd3e480-b683-11eb-8a6f-847db9f30213.png)

What version of PyQtGraph / OS are you on?

I am sure that you have checked that the test code indeed reproduces the problem on your system...
Otherwise my first guess would have been that some other graphics item (possibly the HistogramLUT?) accidentally got added into a wrong spot in the layout(s) and causes the black boxes.

The little [A] is supposed to be there, but it doesn't usually come with a big black box attached to it!

**Comment by RT-Tap** [comment]
Hey so I am running 0.12.1 updated thinking it was part of the issue.  Anyway I figured out that running `app = QtGui.QApplication([]) ` with   `if __name__ == '__main__': pg.mkQApp().exec_()` creates this issue.  I now removed `app = QtGui.QApplication([]) ` and only use `if __name__ == '__main__': pg.mkQApp().exec_()` however I do have a different version of some code where I do use `app = QtGui.QApplication([]) ` with   `if __name__ == '__main__': app().exec_()`  so it seems running 2 application execute methods causes the problem on windows 10 or just my machine.
