### ISSUE TITLE
GLScatterPlotItem: Segmentation fault: 11 on MacOS while addItem

### ISSUE THREAD

**Issue by johanneshauck** [pyqtgraph/pyqtgraph#1787]
Hi everyone,

I had some problems using a QApp on MacOS, which was developed on windows. The problem was a segmentation fault after adding a GLScatterPlotItem to the GLViewWidget.

The following hardware was used:
- Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
- Python 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 08:55:58) [Clang 6.0 (clang-600.0.57)] on MacOS 10.14.6

I added two test files to demonstrate problem and solution in a minimal working example from the pyqtgraph.examples.

testGLScatterPlotItemWin.py runs on windows, but causes a segmentation fault on macOS. Adding the line w.show() in testGLScatterPlotItemMacOS.py fixed the problem and runs on MacOS.

[testGLScatterPlotItem.zip](https://github.com/pyqtgraph/pyqtgraph/files/6509880/testGLScatterPlotItem.zip)

**Comment by j9ac9k** [comment]
Hi @johanneshauck,

Thanks for the example code.

I do get the segfault on macOS when running `testGLScatterPlotItemWin.py` on macOS.  I do not get a segfault running `testGLSCatterPlotItemMacOS.py` on macOS (although that file appears to be using many undefined variables).

I'm not sure what pyqtgraph here could do for the end user here; with the openGL stuff, there are countless platform specific issues you can run to.  We do our best to have example code that works on all platforms, and that's why the examples in the example directory are part of our test suite.

Since python cannot catch segfaults, what do you think pyqtgraph can/should do here instead?

**Comment by pijyoi** [comment]
Actually, this issue is related to the change from QGLWidget to QOpenGLWidget and is not limited to macOS. Since that change, it is a requirement to call ```show()``` on GLViewWidget before adding any items to it.

Now, the catch is that this failure will only occur for those items which make OpenGL calls in their initializeGL method. There are only two of them:
1) GLImageItem
2) GLScatterPlotItem

That's why the first item added ```GLGridItem``` doesn't cause issues.

One way to allow adding of items prior to calling ```show()``` would be to modify the two Items listed above to defer their initialization till ```paint()```. For ```GLImageItem```, that is trivial and should have no impact, since it is only generating a texture id. But that would also mean that ```initializeGL()``` could be removed altogether.

**Comment by j9ac9k** [comment]
@johanneshauck pijyoi submitted a PR to address this issue which was merged fairly recently and the fix will be in the next release of the library.  I just ran the code in the zip file above, and no longer get a segfault (I do get some variables not defined errors tho).  

I'm going to close out this issue, with marking #1871 as the fix.  Thanks for reporting, let us know if this issue is still persistent.
