### ISSUE TITLE
GraphicsLayoutWidget Zoom broken between 0.11.0 and 0.11.1

### ISSUE THREAD

**Issue by maxikrie** [pyqtgraph/pyqtgraph#1798]
### Short description
When using GraphicsLayoutWidget.addPlot with certain style (symbol only) and zooming in, the symbols disappear. This gets even worse with multiple columns of plots, however this minimal example already shows the issue. There was no issue with 0.11.0, and the issue still appears with 0.12.1. 

### Code to reproduce

```python
from PyQt5 import QtCore, QtWidgets

class Ui_GUI(object):
    def setupUi(self, GUI):
        GUI.setObjectName("GUI")
        GUI.resize(1500, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GUI.sizePolicy().hasHeightForWidth())
        GUI.setSizePolicy(sizePolicy)
        GUI.setMinimumSize(QtCore.QSize(1500, 850))
        GUI.setMaximumSize(QtCore.QSize(1500, 850))
        self.graphicsView = GraphicsLayoutWidget(GUI)
        self.graphicsView.setGeometry(QtCore.QRect(0, 10, 1491, 811))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(GUI)
        QtCore.QMetaObject.connectSlotsByName(GUI)

    def retranslateUi(self, GUI):
        _translate = QtCore.QCoreApplication.translate
        GUI.setWindowTitle(_translate("GUI", "GUI"))
        
from pyqtgraph import GraphicsLayoutWidget
from PyQt5.QtCore import QTimer
import sys
import numpy as np
from collections import deque

class Ui(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui, self).__init__()
        self.ui = Ui_GUI()        
        self.ui.setupUi(self)        
        
        self.plot_item = self.ui.graphicsView.addPlot(row = 0, col = 0)
        self.data_item = self.plot_item.plot([], pen=None, symbolBrush=(204,0,0), symbolSize=5, symbolPen=None)
        
        self._timer_update = QTimer(self)
        self._timer_update.timeout.connect(self.update)
        self._timer_update.start(10)
        
        self.data = deque([], maxlen=100*40)
        self.time = deque([], maxlen=100*40)
        self.data.append(0.0)
        self.time.append(0.0)
        self.last_time = 0.0
        
        self.show()
    
    def update(self):
        self.data.append(np.random.rand())
        self.time.append(self.time[-1]+0.01)
        self.data_item.setData(self.time, self.data)
        self.data_item.setPos(-self.time[-1], 0)
        
    def closeEvent(self, event):
        self._timer_update.stop()
        event.accept()

app = QtWidgets.QApplication(sys.argv)
window = Ui()
app.exec_()

```

### Real behavior

```
An error occurred?
Post the full traceback inside these 'code fences'!
```

### Tested environment(s)

 * PyQtGraph version: 0.12.1
 * Qt Python binding: PyQt5 5.15.1
 * Python version: 3.7.3
 * NumPy version: 1.20.3
 * Operating system: Debian 10
 * Installation method: pip3

**Comment by NilsNemitz** [comment]
Hi @maxikrie !
The problem here is the use of `setPos()`. Although this probably comes from our own examples, this is a rather sneaky trick to make the plot draw at an offset position.

The problem is that this basically happens at the graphical level. I did not trace this to the root cause in the code, but a lot of optimization were recently added to the scatter plot. These eliminate "invisible" drawing operations outside the viewport. But by  using the setPos() trick, you are moving the final "image" so that it no longer matches this viewport. That makes it quite noticeable that some points were never drawn. Your code shifts the image to the left, so the missing points on the right should have been outside the screen on the right side.

For the simple lines of the curve plot, drawing is extremely fast, and it is often faster to include all the data. That's why the lines remain visible if you enable them.

The good news is that you don't really need to work with `setPos()` to achieve what you want.
I timed the conversion from a deque to the np.array that PyQtGraph works with internally, and it takes about 300 us when the deque is at the limit you are setting. That is because a deque is (as far as I can tell) a doubly-linked list, and the elements need to be gathered from all over ram to create the "linear" block of data we use internally.

Once you have a NumPy array, further operations are a lot faster: Applying an offset that displays the last point at t=0 takes only 3 us. So if the deque is convenient for you elsewhere, and you can afford the speed penalty, then you can probably afford to do this:
```python
self.data.append(np.random.rand())
self.time.append(self.time[-1]+0.01)
time_relative = np.array(self.time) - self.time[-1]
self.data_item.setData(time_relative, self.data)
```
If you want to go *fast*, you could look at implementing some kind of rolling buffer in a NumPy array. The main advice would be to stick with NumPy data structures and operations as much as possible.

Timing code for deque conversion and NumPy calculation:
```python
for _ in range(4000):
  self.time.append(self.time[-1]+0.01)

repetitions = 100_000

t0 = time.perf_counter()
for _ in range(repetitions):
  arr = np.array(self.time)
dt = time.perf_counter() - t0
print('deque to array took {:.1f} us averaged over {:d} repetitions.'.format(dt/repetitions * 1e6, repetitions) )
        
t0 = time.perf_counter()
for _ in range(repetitions):
  arr2 = arr - 1.0
dt = time.perf_counter() - t0
print('array shift took {:.1f} us averaged over {:0} repetitions.'.format(dt/repetitions * 1e6, repetitions) )
```
deque to array took 312.9 us averaged over 100000 repetitions.
array shift took 3.1 us averaged over 100000 repetitions.

**Comment by maxikrie** [comment]
Great, thanks a lot for the detailed explanation and solution!
