### ISSUE TITLE
Regression: modified zoom behavior with showGrid

### ISSUE THREAD

**Issue by ixjlyons** [pyqtgraph/pyqtgraph#1843]
### Short description

Enabling the grid on a `PlotItem`causes zoom on the `ViewBox` to affect only the y axis when it should affect both. Zooming by scolling on the x axis still works. A more severe side-effect can be seen with `setAspectLocked`.

Bisect points to #1726 - I haven't looked further into it yet, but this should probably hold up 0.12.2 in my view.

### Code to reproduce

```python
import pyqtgraph as pg

app = pg.mkQApp()

p = pg.plot([1, 2, 3], [4, 5, 6])
p.showGrid(x=True, y=True)
#p.setAspectLocked(True)

app.exec()
```

### Tested environment(s)

 * PyQtGraph version: 30bc138
 * Qt Python binding: PyQt5 5.15.4 Qt 5.15.2
 * Python version: 3.9.5
 * Operating system: Linux

**Comment by ixjlyons** [comment]
Narrowed it down to:

https://github.com/pyqtgraph/pyqtgraph/blob/ba517aba0e3dbddb925fcb47f9a0359432fd4a10/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L337

**Comment by j9ac9k** [comment]
that's an amazing MWE.

**Comment by ixjlyons** [comment]
Actually the magic number at least in the example above is -100. Zoom works for any negative value but pan doesn't. That is the z value of the `ViewBox`:

https://github.com/pyqtgraph/pyqtgraph/blob/07a99cb443062940cad20bd20de22d038cf3e982/pyqtgraph/graphicsItems/ViewBox/ViewBox.py#L215

So that answers one question posed in #1728:

> The default Z position of AxisItem has been changed to be 0.1, in order to always draw the axes on top of the image... With the current default of -1000, the ImageItem obscures them completely. I am not aware of the reason for the previous default setting, though.

What we probably want in `PlotItem` is something like `axis.setZValue(self.vb.zValue() - 1)`. Maybe the `- 1` isn't necessary. 

@NilsNemitz could you maybe elaborate on the behavior you're talking about with the `ImageItem` obscuring the axes?

I do see this if I revert the z value change, but I think that may be a bounding rect issue because it only occurs on the left and bottom axes:

![Screenshot_2021-06-18_17-00-08](https://user-images.githubusercontent.com/943602/122624814-cd983000-d056-11eb-9a25-c5ee2ec6ff98.png)

![Screenshot_2021-06-18_17-05-12](https://user-images.githubusercontent.com/943602/122624940-629b2900-d057-11eb-84af-98d88e44ebd6.png)

**Comment by NilsNemitz** [comment]
Dear @ixjlyons ,
That is pretty much what I was trying to avoid.
Ideally, the tick marks should also draw on top of the image, but I guess that could be considered secondary.
I am not sure if there is a reliable solution (across scaling and DPI settings) that clips the graph on the inside of the axis. That would be the ideal hot-fix, though.

I cannot yet comment on the complete z-ordering arrangements, but the change in behavior at z=-100 looks like there is another "fix" somewhere else that moves the viewbox level down so that it doesn't steal mouse events.

So I am expecting that the requirements are (graphs) > viewbox;  viewbox > axes;  axes > (graphs)
That might be hard, so maybe it's best to bump AxisItem back to z-level -1000 and figure out a better solution.

The fundamental issue is that maybe AxisItem shouldn't be drawing the grid?

**Comment by NilsNemitz** [comment]
Dear @ixjlyons , @j9ac9k ,
If we don't mind one additional layer of redirection in handling the mouse events, then we can let AxisItem figure out if the events happened on the axis or the plot area. Then it can account for this information when it passes the event to ViewBox, which it already does.
I hope PR #1845 (or a further evolution) should let us keep the option of placing the axes where they graphically belong without breaking functionality.

**Comment by pijyoi** [comment]
>so maybe it's best to bump AxisItem back to z-level -1000 and figure out a better solution.

I would support such an approach. Revert to -1000, release 0.12.2, then a better solution can perhaps be figured out at a slower pace.

I don't pretend to understand the internals of viewboxes, but it seems more susceptible to unintended behaviours than other parts of the library.
