### ISSUE TITLE
Regression: empty color bar

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#1850]
### Short description

Empty color bar gets plotted instead of Viridis

### Code to reproduce

Example from #1849

### Expected behavior

Expected behavior from #1849 (Viridis color bar)

### Real behavior
![bad_color](https://user-images.githubusercontent.com/2657027/122764172-c597f480-d2d1-11eb-88a4-0407982b1833.png)

### Tested environment(s)

 * PyQtGraph version: master ba517aba0e3dbddb925fcb47f9a0359432fd4a10
 * Qt Python binding: PyQt5 5.15.4 
 * Python version: 3.8.10
 * NumPy version: 1.20.3 
 * Operating system: Windows 10 20H2
 * Installation method: pip install -e .

### Additional context
bisect points to 7d41e8a8789a7037c061f08c6e6e633ba94c4ee3

**Comment by NilsNemitz** [comment]
Dear @pijyoi , dear @paulmueller ,

I am looking at that now.
My current understanding is that the plot shown above is in fact the "expected", documented behavior.
Even if it certainly isn't the desired one.

`stops, colors = cmap.getStops('float')`
tries to get a float description of the colors, the first one is
[0.26666667 0.00392157 0.32941176 1.        ]

A little later
`pg.QtGui.QColor(*[c for c in color]` feeds these into the QColor constructor, which expects integer values 0-255.

I think the plot above is a viridis gradient at opacity 1 out of 255.

The previous code was this:
```python
def getStops(self, mode):
        ## Get fully-expanded set of RGBA stops in either float or byte mode.
        if mode not in self.stopsCache:
            color = self.color
            if mode == self.BYTE and color.dtype.kind == 'f':
                color = (color*255).astype(np.ubyte)
            elif mode == self.FLOAT and color.dtype.kind != 'f':
                color = color.astype(float) / 255.
            self.stopsCache[mode] = (self.pos, color)
        return self.stopsCache[mode]
``` 
And since that did not recognize the 'float' identifier, it silently returned data in the default byte format.

A hotfix to the example code would be to change line 14 to
`stops, colors = cmap.getStops(pg.ColorMap.BYTE)`
which seems to produce the desired color gradient on my system.

I'll look into making a PR that supports string input and probably defaults to the more typical byte format return.

**Comment by pijyoi** [comment]
Closing as issue was due to the example code relying on undefined behaviour that happened to work in older versions of the library.
