### ISSUE TITLE
Issue with colorBarItem 

### ISSUE THREAD

**Issue by vidax40** [pyqtgraph/pyqtgraph#1852]
Hello everyone,
I am facing an issue with colorBarItem.
Indeed, I want to add a colorbar to an imageItem inside a plotItem.
Everything works fine except when i want to update the colorBar. 
If i clear the entire plotItem the previous colorBar remain.

### Short description
Issue when trying to update a colorBar inside an imageItem Plot

### Code to reproduce
```python
import pyqtgraph as pg
import numpy as np
import random
from pyqtgraph.Qt import QtCore, QtGui

# Plot window init
win = pg.GraphicsWindow(title="test", size=(1920, 1080))  # creates a window
win.setBackground("w")
plot = win.addPlot(row=0, col=0)


while True:
    plot.clear()
    
    heatMapData = np.random.rand(64, 64)

    coeff = random.randint(1, 20)

    heatMapData = heatMapData*coeff

    imageData = pg.ImageItem(heatMapData)
    plot.addItem(imageData)

    # Get pyqtgraph colormap from matplotlib
    cm = pg.colormap.get(name="cubehelix", source='matplotlib')
    bar = pg.ColorBarItem(
        values=(np.min(heatMapData), np.max(heatMapData)), cmap=cm)
    bar.setImageItem(
        imageData, insert_in=plot)
    # refresh window
    QtGui.QGuiApplication.processEvents()

```

### Expected behavior
I would like to do an update of the colorBar.
Or remove the previous one and add a new one

### Real behavior
plot.clear() doesn't clear the colorbar

### Tested environment(s)

 * PyQtGraph version: 0.12.1
 * Python version: 
 * NumPy version: 3.8.3 64 bits
 * Operating system: windows
 * Installation method: pip

**Comment by NilsNemitz** [comment]
Dear @vidax40 ,

I am sorry to hear that the ColorBarItem is making trouble.
The way this is currently implemented, the color bar isn't part of the plot, but it instead adds itself as a separate element in the graphics layout. Basically, it works more similarly to `plot` than to the ImageItem `imageData`.

The good news is that you don't really need to reconstruct the entire layout with a new ImageItem and a new ColorBarItem for each update: You can simply set a new image, and if needed, new limits for the ColorBarItem.

Could you try out the following change to your code and let us know if that solves the problem?
```python
from matplotlib import interactive
import pyqtgraph as pg
import numpy as np
from pyqtgraph.Qt import QtCore, QtGui

win = pg.GraphicsWindow(title="test", size=(1920, 1080))  # creates a window
win.setBackground("w")
plot = win.addPlot(row=0, col=0)

imageData = pg.ImageItem()
plot.addItem(imageData)

cm = pg.colormap.get(name="cubehelix", source='matplotlib')
bar = pg.ColorBarItem(cmap=cm, interactive=True)
bar.setImageItem(imageData, insert_in=plot)

while True:
    heatMapData = np.random.rand(64, 64)
    imageData.setImage(heatMapData, autoLevels=False)
    # bar.setLevels( (np.min(heatMapData), np.max(heatMapData)) )
    QtGui.QGuiApplication.processEvents()
```
I turned off the auto-levelling since that competes with the color bar interaction in setting the levels, at least for rapidly refreshing data. If you want the image to auto-level, then you might want to set "interactive=False" for the ColorBarItem.

**Comment by vidax40** [comment]
Thanks everything work fine now 

Regards @NilsNemitz
