### ISSUE TITLE
PlotWidget add label  not working?

### ISSUE THREAD

**Issue by jekoie** [pyqtgraph/pyqtgraph#1955]
I try to use PlotWidget to plot a single view in a window, but when I try to add label, the label work strange.
```python
class Chart1(pg.PlotWidget):
    def __init__(self):
        super().__init__()
        self.label = pg.LabelItem(justify="right")
        self.addItem(self.label)
        self.data1 = np.random.normal(size=100)
        self.data2 = np.random.normal(size=100)

        self.pdi1 = self.plot(self.data1, pen="w")
        self.pdi2 = self.plot(self.data2, pen="g")


        self.vLine = pg.InfiniteLine(angle=90, movable=False)
        self.hLine = pg.InfiniteLine(angle=0, movable=False)



        self.plotItem.addItem(self.vLine, ignoreBounds=True)
        self.plotItem.addItem(self.hLine, ignoreBounds=True)
        self._sigProxy = pg.SignalProxy(self.scene().sigMouseMoved, rateLimit=60, slot=self.mouseMoved)

    def mouseMoved(self, evt):
        pos = evt[0]  ## using signal proxy turns original arguments into a tuple
        vb = self.plotItem.getViewBox()
        if self.sceneBoundingRect().contains(pos):
            mousePoint = vb.mapSceneToView(pos)
            index = int(mousePoint.x())
            self.label.setText(str(index))
            if index > 0 and index < len(self.data1):
                self.label.setText("<span style='font-size: 12pt'>x=%0.1f,   <span style='color: red'>y1=%0.1f</span>,   <span style='color: green'>y2=%0.1f</span>" % (mousePoint.x(), self.data1[index], self.data2[index]))
            self.vLine.setPos(mousePoint.x())
            self.hLine.setPos(mousePoint.y())
```
![image](https://user-images.githubusercontent.com/6836400/128445285-7bcd103f-698a-4c0c-89ea-fa6163c19534.png)

**Comment by j9ac9k** [comment]
I suspect you want to add the label to the embedded PlotItem instead of to the PlotWidget itself.

```python
#        self.addItem(self.label)
#        replace the above with
          self.getPlotItem().addItem(self.label)
```

**Comment by ixjlyons** [comment]
LabelItem is a GraphicsWidget, so it's meant more for being added to a (Q)GraphicsLayout. [TextItem](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/textitem.html) is intended for use within a ViewBox.

**Comment by jekoie** [comment]
@j9ac9k Hi, It has not change anything, It works the same as I my post.

**Comment by jekoie** [comment]
@j9ac9k  Maybe I should use `GraphicsLayout` to it.

**Comment by ixjlyons** [comment]
@jekoie Does replacing your LabelItem with a TextItem not work? You'd need to use something like `anchor=(1, 0)` instead of `justify='right'` and `setHtml` in place of `setText`, but otherwise it should do what you want.

To be clear, LabelItem isn't really working incorrectly here per se -- ViewBox inverts the y axis (Qt uses the y positive down convention) and stretches things according to the current view range. Adding a LabelItem as a child of a ViewBox (which is what `PlotWidget.addItem` ultimately does) means it inherits those transformations. TextItem specifically inverts those transformations so that the text appears the same regardless of ViewBox scaling.

Then again if you don't really need the text to be within the plot itself, you can use a GraphicsLayout and a LabelItem.

**Comment by j9ac9k** [comment]
> ViewBox inverts the y axis (Qt uses the y positive down convention) and stretches things according to the current view range. Adding a LabelItem as a child of a ViewBox (which is what PlotWidget.addItem ultimately does) means it inherits those transformations. TextItem specifically inverts those transformations so that the text appears the same regardless of ViewBox scaling.


I figured this out the hard way while trying to do a custom graphics item with text; probably should put a blurb in the docs about this consideration when doing a custom graphics item.
