### ISSUE TITLE
Pyinstaller issue when running exe

### ISSUE THREAD

**Issue by myue891** [pyqtgraph/pyqtgraph#1981]
Hello,

I am getting an issue only when I try to create an exe using pyinstaller and running that exe file. Everything works fine in my IDE and the GUI works as expected. This is the error I get when I try to run my executable. I have pyqtgraph installed correctly with pip and I can't figure out why this error occurs.

Thanks

<img width="496" alt="Screenshot 2021-09-02 132448" src="https://user-images.githubusercontent.com/55855607/131911242-99482cc0-44a2-4ef4-a169-b38f24909a49.png">

**Comment by j9ac9k** [comment]
Hi @myue891 

This has been discussed in a few places in the issue tracker, if you search for pyinstaller you'll likely see some longer explanation.

Basically because of how pyqtgraph does importing of templates, pyinstaller doesn't know to bundle them.  In my application (I use pyside2 primarily), I have to manually specify the files for pyinstaller to grab:

```
        "pyqtgraph.console.template_pyside2",
        "pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyside2",
        "pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyside2",
        "pyqtgraph.imageview.ImageViewTemplate_pyside2"
```

You likely need to modify your spec file to grab these.

If you're familiar with pyinstaller, and have time/ability to contribute to pyqtgraph, we would love for someone to create a custom hook that would go here: https://github.com/pyinstaller/pyinstaller-hooks-contrib  This has been on the todo for us, but we haven't gotten to it.

**Comment by myue891** [comment]
Hi @j9ac9k 
Thank you for the reply, I found the solution in a similar post.

**Comment by labbeast2020** [comment]
@j9ac9k Hi I have the same issue and this is my spec file 

`# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
import os
import site

ROOT_PATH = os.getcwd()
PACKAGE_SITE= site.getusersitepackages()

print(ROOT_PATH)
print(PACKAGE_SITE)

datas = [(f'{ROOT_PATH}/config', './config'), (f'{ROOT_PATH}/assets', './assets'), (f'{ROOT_PATH}/log', './log')]
datas += collect_data_files('qt_material')

block_cipher = None


a = Analysis([f'{ ROOT_PATH }/main.py'],
             pathex=[ROOT_PATH, r"C:\Users\Beast\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\graphicsItems\ViewBox\axisCtrlTemplate_pyside2.py"],`

**Comment by xuhuasheng** [comment]
I upgraded pyqtgraph==0.13.1 and solved this problem.
env:
  - python==3.8.13
  - pyinstaller==5.2
  - pyqtgraph==0.13.1
  - PyQt5==5.15.4
 
maybe help you.

**Comment by j9ac9k** [comment]
thanks for following up @xuhuasheng 

We removed some of the template files over time and now have none remaining in the library.
