### ISSUE TITLE
Memory leak when calling PlotDataItem.setData

### ISSUE THREAD

**Issue by martmists-gh** [pyqtgraph/pyqtgraph#2158]
### Short description
I've noticed large amounts of memory usage when using setData. To ensure this was a pyqtgraph issue, I made it so it only plotted when enabled, and according to htop it only increased while enabled.

### Code to reproduce
https://github.com/martmists-gh/kaudio-python

Video (setData is only called when the widget is visible):

https://user-images.githubusercontent.com/16361449/146467829-85875a15-90d5-4826-a182-3d3e7b54cafe.mp4

### Tested environment(s)

 * PyQtGraph version: 0.12.3
 * Qt Python binding: PySide2 5.15.2 Qt 5.15.2
 * Python version: Python 3.10.1
 * NumPy version: 1.21.4
 * Operating system: Arch Linux
 * Installation method: pip

**Comment by pijyoi** [comment]
Could you try the following experiment on your setup:
1. run the Examples App : `python -m examples`
   * if you are using the master branch, that has changed to `python -m pyqtgraph.examples`
2. search for `Benchmarks -> Line Plot update`
3. in the code panel, search for `class MonkeyCurveItem(pg.PlotCurveItem):` and replace it with `class MonkeyCurveItem(pg.PlotDataItem):`
   * this change is because your code is using a `PlotDataItem`
4. click on `Run Edited Code`
5. check to see if there is continuous memory growth

Note: I don't have the exact same environment as you, but neither running `pyqtgraph 0.12.3` nor `master` on my setup shows any continuous memory growth.

**Comment by martmists-gh** [comment]
That doesn't seem to cause any noticeable problems.

**Comment by j9ac9k** [comment]
@martmists-gh if I'm interpreting your video correctly, the issue seems to be when you switch to the FFT tab?

Also, the environment you have is a bit odd; there is no PySide2 wheel for python 3.10.  First thing I would try is migrating to either PyQt5 (which I believe has a Python 3.10 wheel) or migrating to Qt6 6.2 (either PyQt6 or PySide6).

Lastly, I think this kind of environment you have is just going to be too difficult for us to replicate given that it requires non-python related dependencies. I would suggest modifying one of the examples, specifically the the Line Plot Update one that @pijyoi referenced above, and make the calls to it match your application to the best of your ability and test that.  If you can replicate a memory leak there, we can certainly take a closer look.
