### ISSUE TITLE
`prepareForPaint` not connected to `sigPrepareForPaint`

### ISSUE THREAD

**Issue by nicoddemus** [pyqtgraph/pyqtgraph#2217]
Hi!

First of all thanks a lot for the excellent plotting library, probably one of the best out there for Qt. :thumbsup:

I'm posting this because I'm seeing a regression when updating from `0.12.2` to `0.12.3`/`0.12.4` in my tests.

This is the error:

```
Traceback (most recent call last):
  File "...\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 292, in itemChange
    scene.sigPrepareForPaint.disconnect(self.prepareForPaint)
TypeError: 'method' object is not connected
```

Here's the relevant method:

https://github.com/pyqtgraph/pyqtgraph/blob/cd855bd79b22476d6de3211cf57150abbe7edf5b/pyqtgraph/graphicsItems/ViewBox/ViewBox.py#L286-L296

This hints that the ViewBox's scene has changed during the run. 

I'm pretty sure the error is on my side, but I'm posting here in the hopes someone can point me to the right direction to debug the problem.

Unfortunately I cannot reproduce the problem in a minimal working example.

**Environment**

* PyQtGraph version: `0.12.4` (also happens in `0.12.3`, does not happen in `0.12.2`).
* Qt Python binding: `PyQt5 5.15.6 Qt 5.15.2`
* Python version: `3.10.2`
* NumPy version: `1.22.2`
* Operating system: Windows
* Installation method: `pip-22.0.3`.

Tests run with `pytest-qt`.

Any hints?

Thanks!

**Comment by nicoddemus** [comment]
Thanks @j9ac9k for the quick response!

Thanks to your suggestion, I managed to write a minimal working example:

```python
from pyqtgraph import ViewBox, PlotItem, GraphicsLayoutWidget


class MyViewBox(ViewBox):
    def __init__(self, parent=None) -> None:
        super().__init__(parent=parent)
        self.plot_item = PlotItem(parent=parent, viewBox=self)


class MyGraphPanel(GraphicsLayoutWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.view_boxes = []

        view_box = MyViewBox(parent=self.centralWidget)
        self.view_boxes.append(view_box)
        self.addItem(view_box.plot_item)


def test_reproducer(qtbot):
    graph = MyGraphPanel()
    qtbot.addWidget(graph)
    graph.clear()
``` 

Executing this I get:

```
λ pytest Edgar\test_reproduce.py --no-header
============================= test session starts =============================
collected 1 item

Edgar\test_reproduce.py F                                                [100%]

================================== FAILURES ===================================
_______________________________ test_reproducer _______________________________
CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "..env310\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 292, in itemChange
    scene.sigPrepareForPaint.disconnect(self.prepareForPaint)
TypeError: 'method' object is not connected
________________________________________________________________________________
---------------------------- Captured stderr call -----------------------------
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "..env310\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 292, in itemChange
    scene.sigPrepareForPaint.disconnect(self.prepareForPaint)
TypeError: 'method' object is not connected
________________________________________________________________________________
=========================== short test summary info ===========================
FAILED Edgar/test_reproduce.py::test_reproducer
============================== 1 failed in 0.32s ==============================
```

Anything there jumps to the eyes? I would also be glad to put that in a repository together with a proper `requirements.txt` if that helps.

**Comment by j9ac9k** [comment]
I'll tinker with the code when I'm done "working"; but there are two things that stand out to me.

1. first thing that stands out is we generally try and make it so that users don't need to define `parent` relationships.  This is a bit odd for those more familiar with Qt, but the general assumption is unless you're doing something really odd, users should not specify "parent" anywhere, pyqtgraph should be able to sort this out correctly.  Due to handling of references and such, I would even go as far as to say that it's much preferable to let pyqtgraph sort out the parent relationships.
2. We expect the parent of the ViewBox to be the PlotItem that has the ViewBox baked in.  In your example, you have the subclassed ViewBox be the parent for the subclassed PlotItem.  I'm not saying what you're doing is wrong, but just that it's a bit backward from what we expect here.  A more common use case is to create a subclass of a ViewBox, and pass that instance into `PlotItem(viewBox=mySubclassedViewBoxInstance)`

For the record, I'm not opposed to adding some logic to handle this exception more gracefully; but not having this signal connected can lead to some weird behavior that would be hard to otherwise identify, so at the very least we should emit a warning.

**Comment by nicoddemus** [comment]
I see, thanks @j9ac9k for the analysis, appreciate it.

I removed both `parent` and `viewBox` parameters passed to `PlotItem` and the problem goes away, both in the reproducer and in the test suite. Also in the live application it seems to be working fine, so I'm guessing that solves it. 

I guess when pyqtgraph started connecting to that signal and making that check in `0.12.3`, it exposed the API misuse on my part.

From my POV we can close this issue. 👍 

Thanks again @j9ac9k for pointing me to the right direction!

**Comment by j9ac9k** [comment]
👍🏻 

The change we made in 0.12.2 was primarily for performance reasons (we removed an explicit call to `prepareForPaint` inside the `paint` method, now `prepareForPaint` is only called when needed).  Because of that explicit call, I doubt that you had any errors before.

If you don't mind me asking, in your use-case do you overlay multiple ViewBox?  That's a common thread I've seen (and a feature we're working on rolling out).

**Comment by nicoddemus** [comment]
> If you don't mind me asking, in your use-case do you overlay multiple ViewBox? That's a common thread I've seen (and a feature we're working on rolling out).

Not at all. I show the plots side by side on a grid, not some overlapping one on the top of the other (that's what I understand by "overlay").

**Comment by j9ac9k** [comment]
> > If you don't mind me asking, in your use-case do you overlay multiple ViewBox? That's a common thread I've seen (and a feature we're working on rolling out).
> 
> Not at all. I show the plots side by side on a grid, not some overlapping one on the top of the other (that's what I understand by "overlay").

A frequent feature request we've had is to put two plots with different axes scales on top of each other; while a lot of effort has been made to attempt to make a single-viewbox handle this we've been unsuccessful there, so the typical method people have implemented is by putting multiple viewboxes (or PlotItems) on top of one another and doing funky things w/ a `GraphicsLayout` to have the axes stack in such a way that they don't overlap.

Thanks for sharing; and again, if you have any questions, please reach out.

**Comment by nicoddemus** [comment]
> A frequent feature request we've had is to put two plots with different axes scales on top of each other; while a lot of effort has been made to attempt to make a single-viewbox handle this we've been unsuccessful there, so the typical method people have implemented is by putting multiple viewboxes (or PlotItems) on top of one another and doing funky things w/ a GraphicsLayout to have the axes stack in such a way that they don't overlap.

That sounds useful! We have custom implementations (based on PyQwt) to accomplish that. It would be awesome if pyqtgraph supported this.

> Thanks for sharing; and again, if you have any questions, please reach out.

Sure, and thanks again. 👍

**Comment by j9ac9k** [comment]
Hi @nicoddemus 

I'll try and take a closer look later today; while this example seems a bit odd to me, at a glance I'm not seeing anything that should prevent it from working.  I say odd as _typically_ we don't expect a PlotItem to be an attribute of a subclassed ViewBox, but just because it's odd doesn't mean it shouldn't work.

Indeed passing in a specific viewbox into PlotItem can only happen during `__init__` (I'm open to giving a method for this to allow this functionality outside of `__init__`, we just haven't had such a feature request).

> Sorry if I'm misunderstanding, but I think that's what's happening in there? The custom view box is passed to the `PlotItem` via parameter (a bit odd that the view box also owns the PlotItem via an attribute, but that seems to be a "valid" although odd design).

yeah, I think you and I are on the same page; this should work, but it doesn't.

**Comment by nicoddemus** [comment]
>  I say odd as typically we don't expect a PlotItem to be an attribute of a subclassed ViewBox, but just because it's odd doesn't mean it shouldn't work.

Indeed, so I took that oddity out in order to reduce the MWE even further:

```python
from pyqtgraph import ViewBox, PlotItem, GraphicsLayoutWidget


class MyGraphPanel(GraphicsLayoutWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.view_box = ViewBox(parent=self.centralWidget)
        self.plot_item = PlotItem(viewBox=self.view_box)
        self.addItem(self.plot_item)


def test_reproducer(qtbot):
    graph = MyGraphPanel()
    qtbot.addWidget(graph)
    graph.clear()
```

This still gives the same error. 

> yeah, I think you and I are on the same page; this should work, but it doesn't.

Indeed. Thanks for looking into this, really appreciate it. 👍

**Comment by j9ac9k** [comment]
@nicoddemus Actually, I take that back

```python
        self.view_box = ViewBox(parent=self.centralWidget)
```

remove the `parent=self.centralWidget` argument and this should work.  If you're looking to have the item added to the GraphicsLayoutWidget, having `GraphicsLayoutWidget.addItem()` should be sufficient.   Would that change break the use-case you're trying to represent?

**Comment by nicoddemus** [comment]
>  Would that change break the use-case you're trying to represent?

Yes, thanks! (sorry for taking so long to respond).

So it seems the takeway is: 

> Avoid passing `parent` around, leave pyqtgraph to figure it out; `parent` should only be passed on to the top-level structures (such as `PlotWidget`).

Is that correct?

Closing this now then. Thanks again @j9ac9k for the incredible support. 👍

**Comment by j9ac9k** [comment]
Hi @nicoddemus 

I just want to make sure that _not_ specifying a `parent` here is doable for your use case.  If that's not feasible, I'm happy to assist you with trying to identify alternative workarounds.

**Comment by nicoddemus** [comment]
> I just want to make sure that not specifying a parent here is doable for your use case. 

Yes it is, right afterwards we would call `addItem` to add the viewbox to the scene anyway. 👍
