### ISSUE TITLE
OpenGL on windows slows things down

### ISSUE THREAD

**Issue by jankap** [pyqtgraph/pyqtgraph#2227]
I'm trying to combine rapidly updating line plots with a 3d mesh plot. I realized that the 3d plot implicitely activates OpenGl and slows everything down. 

To reproduce, I use the the "Multiple Plots" example with this line added:

`pg.setConfigOptions(antialias=False, useOpenGL=True)` 

it slows down from 65 fps to 44 fps. In my real application I update two scatter plots (PlotWidget) over time and the 3d mesh via Qt Timer with 50 ms. Reducing it to < 30 ms freezes the complete GUI and the window does not respond anymore.

The CPU load is only at ~12% (might be one core), GPU is at 3%. Tried to force the dedicated Nvidia GPU to render the GUI but no difference.

Is a slowdown expected, or am I doing something wrong presumably?

Specs: Windows 10, Python 3.10, pyqtgraph 0.12.4, everything in a pipenv, Dell Precision 7560

Thank you very much!

**Comment by j9ac9k** [comment]
Hi @jankap 

Would you by chance be able to share the code you used to generate those plots?

**Comment by jankap** [comment]
Hi @j9ac9k

I knew this question was coming ;) currently it's code I can't share, but I'm working on a minimal example. 

Quick update: By adapting the awesome remote plotting example,  I could stabilize framerates at ~30 fps with OpenGL. So far no crashes which is good. 

Will try to provide the example nevertheless. I just thought there are rules like "do not use OpenGL on Windows" or "a performance impact is expected" or so :)

**Comment by j9ac9k** [comment]
there are loads of oddities everywhere with OpenGL, and truth be told our implementation is likely not the safest either.  We would certainly welcome feedback on our OpenGL implementation haha.

Odd the remote plotting example would work here when the non-remote plotting one wouldn't... but eh, who am I to argue.

**Comment by pijyoi** [comment]
>To reproduce, I use the the "Multiple Plots" example with this line added:
```
pg.setConfigOptions(antialias=False, useOpenGL=True)
```

This causes the `QGraphicsView` system that `pyqtgraph` uses to use a `QOpenGLWidget` instead of a `QWidget` for its backend. This changes the underlying drawing engine that `Qt` uses. The plotting differences that you see are a result of this. One other thing that I have noticed before is that using `OpenGL=True` will result in loss of sub-pixel font rendering.
Using this as a "reproducing" example is not quite the same as your actual application.

I wouldn't recommend setting `OpenGL=True`. In fact, on Linux and macOS, line plotting will slow drastically to a crawl.

On Windows, at least, the moment a `QOpenGLWidget` is used, vsync will be enabled. What gets drawn in the `QOpenGLWidget` is actually offscreen, and the rendered buffer is composited by Qt with the rest of any non-OpenGL widgets, which in this case is your `PlotWidget`.
You could try disabling vsync, as is in done in:
https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/examples/VideoSpeedTest.py

>Will try to provide the example nevertheless. I just thought there are rules like "do not use OpenGL on Windows" or "a performance impact is expected" or so :)

What you are doing "different" from the examples that pyqtgraph provides is using a `QOpenGLWidget` with other `QWidgets`. This is not wrong and is absolutely permitted by Qt. It's just that we do not have the experience to know of any "gotchas".

**Comment by j9ac9k** [comment]
@jankap I suppose I should add that if you really want/need hardware acceleration for rendering here, you should probably take a closer look at VisPy.  From our perspective, pyqtgraph has a much more robust API for capturing interactivity, more plot types, and so on, but VisPy will likely outperform pyqtgraph's rendering capability due to highly optimized OpenGL (and they're working on other backends now too).

**Comment by jankap** [comment]
Thanks for all your answers. I will try vsync and the other proposals.

>  I suppose I should add that if you really want/need hardware acceleration for rendering

I do not want it badly ;) What I would like to accomplish is a GUI with line plots and a rendering of a mesh, originating from a .stl file. That's why I thought that OpenGL is required. Are there any other 2d ways to render and rotate a mesh?

> I wouldn't recommend setting OpenGL=True. In fact, on Linux and macOS, line plotting will slow drastically to a crawl.

I had the impression, that once QOpenGLWidget and PlotWidget (QWidgets) get mixed, everything is set to use OpenGL. Is that impression wrong?

Thanks!

**Comment by j9ac9k** [comment]
> I had the impression, that once QOpenGLWidget and PlotWidget (QWidgets) get mixed, everything is set to use OpenGL. Is that impression wrong?

Specifying `useOpenGL=True` will force the widget to use `QOpenGLWidget` instead of `QWidget`;  but that does not guarantee that you will use the `paintGL` methods as opposed to `paint`

**Comment by j9ac9k** [comment]
I will close out this issue since I'm not sure there is anything else for up to implement.  For the time being we consider the opengl 2D implementation to below the performance of the non-openGL variant.
