### ISSUE TITLE
arrow key navigation in table widget

### ISSUE THREAD

**Issue by chanansh** [pyqtgraph/pyqtgraph#240]
Hi. Good job with pyqtgraph!. I like it!.
According to the manual of pyqt: "You can navigate the cells in the table by clicking on a cell with the mouse, or by using the arrow keys. Because QTableView enables tabKeyNavigation by default, you can also hit Tab and Backtab to move from cell to cell.".

However, when I create a table in pyqtgraph, I cannot navigate with arrow keys. This is true even for the TableWidget example in pyqtgraph.

Do you know how to make this work without the need to handle key events?

Hanan.

**Comment by ixjlyons** [comment]
It looks like `pg.TableWidget` catches Ctrl+c key press events but doesn't pass along others to the parent class (`QTableWidget`). I don't see a good reason for ignoring them, so I think it's a bug that should be fixed. Here's a workaround that should work for now:

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtGui

class MyTableWidget(pg.TableWidget):
    def keyPressEvent(self, event):
        pg.TableWidget.keyPressEvent(self, event)
        QtGui.QTableWidget.keyPressEvent(self, event)
```

As a side note, since you referred to the `QTableView` docs: be aware that `QTableView` and `QTableWidget` are different. *Widgets* use the standard interface you're probably used to, whereas *Views* are based on [model/view programming](http://doc.qt.io/qt-4.8/model-view-programming.html).

**Comment by chanansh** [comment]
Thanks. by the way:
1. do you have an example of pandas dataframe as TableModel for a TableView?
2. do you know how can I get the correct row number after sorting?
