### ISSUE TITLE
How to set properly key binding

### ISSUE THREAD

**Issue by bilaljo** [pyqtgraph/pyqtgraph#2410]
Hello,

I wanted to bind some keys (space bar, e.g. to pause the program), during overwriting the method:

```
class Plotting(pg.GraphicsLayoutWidget):
    pressed_key = pyqtSignal(int)

    def __init__(self, receiver):
        self.pressed_key.connect(self.on_key)

    def keyPressEvent(self, ev):
        self.pressed_key.emit()
        self.pressed_key(ev)
        print("here")

    def on_key(self, key):
        print("key pressed")
```

However, after clicking the keys, nothing happened. How should I bind the keys properly? 

Thanks in advance.

**Comment by j9ac9k** [comment]
Hi @bilaljo 

There are a few issues w/ your code.  

1. You're not calling the superclass init method of your `Plotting` class
2. You define your signal as containing an `int`, but when you emit the signal, you pass no such `int` into it.
3. You are treating your signal as a `callable`.

I modified your example here so that it runs without error:

```python
import pyqtgraph as pg
from PyQt6.QtCore import pyqtSignal


app = pg.mkQApp()

class Plotting(pg.GraphicsLayoutWidget):
    pressed_key = pyqtSignal(int)

    def __init__(self):
        super().__init__()
        self.pressed_key.connect(self.on_key)

    def keyPressEvent(self, ev):
        self.pressed_key.emit(ev.key())
        print("here")

    def on_key(self, key):
        print("key pressed")


if __name__ == "__main__":
    plot = Plotting()
    plot.show()
    pg.exec()
```

Hope this helps!

**Comment by bilaljo** [comment]
Thank you for the explanation! Key capturing works perfectly now.
