### ISSUE TITLE
Current pyqtgraph version

### ISSUE THREAD

**Issue by arktrin** [pyqtgraph/pyqtgraph#2422]
Currently If I install the latest pyqtgraph from the master branch I will get the 0.12.4dev version. But the latest release is 0.12.4 - so if I do `pip install pyqtgraph --upgrade` I will be downgraded from the latest master (0.12.4dev) to 0.12.4. 

I remember the time when the latest commit short hash was added to version number.

**Comment by j9ac9k** [comment]
Hi @arktrin 

Are you suggesting that we make the version be dynamically created based on the commit of the current hash in the repo? I've attempted that in other projects, but ran into trouble when people were using the project but outside of a git repository... I would certainly be open to a PR to support this.

**Comment by arktrin** [comment]
@j9ac9k Hello!

> make the version be dynamically created based on the commit of the current hash in the repo?

Yes, like that. 

> ran into trouble when people were using the project but outside of a git repository

Do they bother of the version anyway ?

**Comment by j9ac9k** [comment]
So the issue you ran into was due to a mistake I made regarding migrating dev versions; it shouldn't happen again.

After looking through the [documentation for the packaging library](https://packaging.pypa.io/en/stable/index.html), and reviewing PEP 440, I'm going to close this issue out:

[PEP 440](https://peps.python.org/pep-0440/#dvcs-based-version-labels)
> As hashes cannot be ordered reliably such versions are not permitted in the public version field.
