### ISSUE TITLE
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QGraphicsEllipseItem'

### ISSUE THREAD

**Issue by Manypopes** [pyqtgraph/pyqtgraph#2524]
I have used a QGraphicsEllipseItem to draw a circle on a plot. 

```
circle = pyqtgraph.QtGui.QGraphicsEllipseItem(-10, -10, 20, 20)`
    `circle.setPen(pyqtgraph.mkPen(0.2))`
    `self.plot_polar_curve.addItem(circle)
````

I noticed that in my global Python environment this would run file, however in a venv with only PyQt5 and pyqtgraph installed I would get the error `AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QGraphicsEllipseItem'`.

I've instead imported it through PyQt5 but thought I'd report it here.
`from PyQt5.QtWidgets import QGraphicsEllipseItem`

**Comment by j9ac9k** [comment]
Hi @Manypopes 

I'm not sure what the issue is, you are trying to import QGraphicsEllipseItem from pg.Qt.QtGui module, not pg.Qt.QtWidgets.

While pyqtgraph users are free to use the Qt abstraction layer (pyqtgraph.Qt); we advise against doing so.  We only abstract the parts of the Qt bindings we need for pyqtgraph, and may not cover your use case.

In your example, likely changing `circle = pyqtgraph.QtGui.QGraphicsEllipseItem` to `circle = pyqtgraph.QtWidgets.QGraphicsEllipseItem` should fix your code.

**Comment by Manypopes** [comment]
Ok no worries!
