### ISSUE TITLE
`test_rescaleData` fails on aarch64

### ISSUE THREAD

**Issue by ggardet** [pyqtgraph/pyqtgraph#2645]
### Short description
`test_rescaleData` fails on aarch64:
```
[  551s] =================================== FAILURES ===================================
[  551s] _______________________________ test_rescaleData _______________________________
[  551s] [gw2] linux -- Python 3.8.16 /usr/bin/python3.8
[  551s] 
[  551s]     def test_rescaleData():
[  551s]         dtypes = map(np.dtype, ('ubyte', 'uint16', 'byte', 'int16', 'int', 'float'))
[  551s]         for dtype1 in dtypes:
[  551s]             for dtype2 in dtypes:
[  551s] >               data = (np.random.random(size=10) * 2**32 - 2**31).astype(dtype1)
[  551s] E               RuntimeWarning: invalid value encountered in cast
```

### Code to reproduce
Run tests on openSUSE Tumbleweed aarch64.

### Expected behavior
Test should pass.

### Real behavior
Test fails.

### Tested environment(s)

 * PyQtGraph version: 0.12.4 and 0.13.1
 * Qt Python binding: 6.4.2
 * Python version: 3.8.16
 * NumPy version: 1.24.1
 * Operating system: openSUSE Tumbleweed aarch64
 * Installation method: from source

**Comment by mweinelt** [comment]
Fails in the same way on aarch64-linux on nixpkgs with pyqtgraph 0.12.2 on Python 3.10.10, with pyqt 5.15.9, numpy 1.24.2.

**Comment by j9ac9k** [comment]
would love to attempt to fix it, but I don't have access to this platform for debugging

**Comment by pijyoi** [comment]
I can achieve the same warning on x86-64:
```python
In [6]: (np.array(1.0, dtype=np.float64) * 2**32 - 2**31).astype(np.int32)
<ipython-input-6-0c74f3ae7e1a>:1: RuntimeWarning: invalid value encountered in cast
  (np.array(1.0, dtype=np.float64) * 2**32 - 2**31).astype(np.int32)
Out[6]: -2147483648
```

However `np.random.random` is only supposed to return values in the interval `[0.0, 1.0)`.
Yet `np.random.Generator.uniform` warns that although it is supposed to return in the interval `[low, high)`, due to floating point rounding, the "high" value may get included.

So I am wondering if we are getting a 1.0 from `np.random.random` on aarch64.

There's also a numpy issue on aarch64 fma
https://github.com/numpy/numpy/issues/22993

The random seed is set to `12345` at the start of `test_functions.py`. So perhaps the OP could try to change that value and see if the error still occurs.

It should be noted that the `np.random.xxx` functions that the pyqtgraph library uses throughout is no longer the numpy recommended way of obtaining random numbers. The recommended way is by using `np.random.default_rng()`.

**Comment by j9ac9k** [comment]
Ahh didn't realize there is a new recommended way of getting random values.  Probably would be a good first issue to migrate our usage.

**Comment by swt2c** [comment]
Hi, I did some investigation on this issue.  This issue is also a problem on s390x and ppc64le.

The issue is not that `np.random.random` is returning a 1.0, but that the subtraction of `2**31` leads to negative float values.  Apparently, conversion of negative floats to `ubyte` is undefined on aarch64, s390x and ppc64le.  The same issue happens for `uint16t` on s390x but not the other platforms, interestingly.

**Comment by pijyoi** [comment]
If it is convenient for you, could you test #2748?
It might fix the `RuntimeWarning` in the original post, but perhaps it might expose more errors.

**Comment by swt2c** [comment]
Yes, I'll try it tomorrow or the next day.

**Comment by ggardet** [comment]
I confirm that https://github.com/pyqtgraph/pyqtgraph/pull/2748 fixes this test issue.
