### ISSUE TITLE
ViewBox.viewPixelSize() returns 0.0 for values below 1E-17

### ISSUE THREAD

**Issue by nup002** [pyqtgraph/pyqtgraph#2716]
Calling viewPixelSize() of a ViewBox() is meant to return the size of a pixel in the local coordinate system. This works as expected, until the pixel size drops below 1E-17, after which it returns 0.0. 

### Code to reproduce
```
import pyqtgraph as pg

def print_pixel_size(viewbox, viewRange, changed):
    view_pixel_size = viewbox.viewPixelSize()
    print(f"X pixel size: {view_pixel_size[0]}, Y pixel size: {view_pixel_size[1]}")

app = pg.mkQApp()
p = pg.plot()
p.plotItem.getViewBox().sigRangeChanged.connect(print_pixel_size)
app.exec()
```
Scroll in until the printed values reach 1E-17. Continuing zooming in will print 0.0. 

This is perhaps not an issue for most users, but in my case it breaks the functionality of my app.

**Comment by j9ac9k** [comment]
Hi @nup002 

You'll notice if you zoom in around (0, 0), you can actually get much finer detail

![image](https://github.com/pyqtgraph/pyqtgraph/assets/646398/0cb503a7-bb96-438a-bc0f-b48a33f80350)

```
X pixel size: 1.57689285343271658594929443564769110765129032420834472071926e-80, Y pixel size: 0.00218340611353706748332115239463746547698974609375
```

I modified your script slightly to print out as much precision as I could get:

```python
    print(f"X pixel size: {view_pixel_size[0]:.60g}, Y pixel size: {view_pixel_size[1]:.60g}")
```

Given that floating point values are not evenly distributed, this suggests to me that you're operating a range of values (around +/- 1.0) where the difference between adjacent values is so small, that we're not able to differentiate between them sufficiently.

Looking at https://float.exposed (a fantastic website) we see that around 1e-17, the next adjacent value is +/- 1.5e-33, and that's close enough that I can see some of the matrix math would be ...problematic.

https://float.exposed/0x3c670ef540000000

I do want to say that pyqtgraph already goes through some extreme pains to accommodate very small differences in values, as we do whatever we can to avoid `QTransform.inverted()`; we have our own method to compute inverse transforms that avoid Qt's `qFuzzyIsNull` rounding of errors:

* [pyqtgraph's invertQTransform method](https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/functions.py#L3011-L3026)
* [qt's attempt to clip off small values](https://github.com/qt/qtbase/blob/dev/src/gui/painting/qtransform.cpp#L332)

If you see a way that we can retain more precision than currently w/o significantly impacting performance, we want to hear about it, but as of right now, we are doing the best we know how to do.

**Comment by nup002** [comment]
Thank you for your reply, [j9ac9k](https://github.com/j9ac9k). I am not sure I understand the explanation you are giving me, but I am happy to hear you are aware of it.

**Comment by j9ac9k** [comment]
Hi @nup002 

It was getting late last night so I didn't do a good job explaining, I'm sorry.  What your issue comes down to is that spacing between adjacent floating point values is not uniform over the entire number range.  

For example, for a double/float64 dtype, the next adjacent value to 0.0 is +/- 4.94e-324.   At 1.0, the next value in the positive direction is 1.0+2.22e-16 (and the next value down is 1.0-1.11e-16).  At 1000.0, the next adjacent value is 1000 + 1.14e-13.  So we have super fine precision (on the order of 10^-324!) near 0.0, but as numbers get larger, we start to lose that precision of what numbers floats can represent.

Your issue is that you not only are you working with small values, but you're working with values in a number range that 64-bit floats cannot make accurate calculations within due to a lack of precision.  There is some math that happens behind the scenes when you query what is your view pixel size, and due to the limitation of precision of floating points, pyqtgraph/numpy/qt is giving you answers that don't line up with what you think you should be seeing by doing the math on paper.

So, in your use case, what can you do?  Well, if you're working with _very_ small values, you should try and keep them around 0.0, where floating points can be represented w/ the greatest precision available.

Funny enough, this is the second pyqtgraph-related issue involving floating point precision I've had to examine closely in a week 😆   If you're curious to learn more, I recommend tinkering w/ https://float.exposed  and if you're wanting to know why it works like that, there are many blog posts out there on how floating point precision works.

Python does offer the decimal module, which can be used to present values with even greater precision than floats, but this would likely kill performance which is why we haven't explored it more.
