### ISSUE TITLE
SVGExporter fails

### ISSUE THREAD

**Issue by CPrescher** [pyqtgraph/pyqtgraph#2789]
### Short description
The SVGexporter does not work anymore.

### Code to reproduce

```python
import pyqtgraph as pg
import pyqtgraph.exporters

# generate something to export
plt = pg.plot([1,5,2,4,3])

# create an exporter instance, as an argument give it
# the item you wish to export
exporter = pg.exporters.SVGExporter(plt.plotItem)

# set export parameters if needed
exporter.parameters()['width'] = 100   # (note this also affects height parameter)

# save to file
exporter.export('fileName.svg')
```

### Expected behavior

create a functional SVG plot of the graph

### Real behavior

NotImplemented Error and SVG output is incorrect

```
NotImplementedError: QGraphicsObject.paint() is abstract and must be overridden
```

### Tested environment(s)

 * PyQtGraph version: 0.13.3 
 * Qt Python binding: 'PyQt6 6.5.2 Qt 6.5.2' 
 * Python version: 3.11.2
 * NumPy version: 1.24.4 
 * Operating system:  Windows 11
 * Installation method: poetry (e.g. pip)

**Comment by j9ac9k** [comment]
While the console prints that message out, is a SVG not generated?

I know why that message is printed, it has to do w/ PlotDataItem not having a paint method defined, however its children, PlotCurveItem and ScatterPlotItem do.  Since the children do have that method defined, a valid SVG should still be generated.

**Comment by CPrescher** [comment]
a svg is generated, but only showing part of the plot

**Comment by j9ac9k** [comment]
> a svg is generated, but only showing part of the plot

I'll have to take a closer error, that Error you posted in the real behavior should be able to be ignored safely (was considering even suppressing it when I was last working in the SVG code).  If the exported SVG only shows part of the plot, that's an unrelated issue.

**Comment by pijyoi** [comment]
Exporting has traditionally required an `app.processEvents()` just prior to the export.
After adding that to your code, I am getting the following results:
1) pyqtgraph 0.12.1 to 0.13.3 exports wrongly
2) pyqtgraph since commit 760d85c6cd2a5f3892bf2f242158bb949df3d80f (2023/06/05) exports correctly.

Could you test against `master` branch?

**Comment by CPrescher** [comment]
I can confirm that it is working now. Thanks!

**Comment by j9ac9k** [comment]
> I can confirm that it is working now. Thanks!

Thanks for checking!
