### ISSUE TITLE
uic doesn't exist in pyqt6

### ISSUE THREAD

**Issue by lead-fiend** [pyqtgraph/pyqtgraph#2824]
### Short description
uic doesn't exist in pyqt6

### Real behavior

```
File "/home/lead-fiend/.local/lib/python3.11/site-packages/pyqtgraph/Qt/__init__.py", line 188, in <module>
    from PyQt6 import sip,  uic
ImportError: cannot import name 'uic' from 'PyQt6' (/usr/lib/python3/dist-packages/PyQt6/__init__.py)


```

### Tested environment(s)

 * PyQtGraph version: pyqtgraph-0.13.3
 * Qt Python binding: 6
 * Python version: 3.11
 * Operating system: Ubuntu 23.04

### Additional context
Have looked at the file list for package python3-pyqt6 for Ubuntu 22.10 and 23.04 and both indicate that uic doesn't exist in v6 binding. Works perfectly with v5 binding

**Comment by pijyoi** [comment]
I don't have Ubuntu > 22.04 at the moment, but on both Fedora 38 and openSUSE Tumbleweed, the distro packaged PyQt6 does come with PyQt6.uic.
```
$ python3 -c "import PyQt6; print(PyQt6.__path__); from PyQt6 import uic"
['/usr/lib64/python3.11/site-packages/PyQt6']
```

**Comment by ksunden** [comment]
While it is provided by the pypi package directly, it looks like on debian-based systems `uic/__init__.py` is included with the `pyqt6-dev-tools` package rather than the `python3-pyqt6` package... which is odd and frustrating, as it is included with `python3-pyqt5`

But I suspect installing that package should work...

**Comment by lead-fiend** [comment]
Thanks ksunden, installing pyqt6-dev-tools fixed it.
