### ISSUE TITLE
GLGridItem ignores color argument

### ISSUE THREAD

**Issue by flutefreak7** [pyqtgraph/pyqtgraph#283]
If I try to create a GLGridItem with a different color grid (like for gray grid on white background), it doesn't do anything with the color argument.  In the paint method, It appears the color is set with `glColor4f(1, 1, 1, .3)`.

**Comment by flutefreak7** [comment]
Thank you ixjlyons for adding this functionality!

Since this change isn't in the version I have installed I implemented ixjlyons fix using a subclass:

    class Grid(gl.GLGridItem):

        def __init__(self, color=None, **kwargs):
            super().__init__(self, **kwargs)

            if color is None:
                color = (255, 255, 255, 80)
            self.setColor(color)

        def setColor(self, args):
            """
            Set the color of the grid. Arguments are the same as those accepted by
            :func:`glColor <pyqtgraph.glColor>`.
            """
            self.color = fn.glColor(args)

        def paint(self):
            self.setupGLState()

            if self.antialias:
                glEnable(GL_LINE_SMOOTH)
                glEnable(GL_BLEND)
                glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
                glHint(GL_LINE_SMOOTH_HINT, GL_NICEST)

            glBegin(GL_LINES)

            x, y, z = self.size()
            xs, ys, zs = self.spacing()
            xvals = np.arange(-x / 2., x / 2. + xs * 0.001, xs)
            yvals = np.arange(-y / 2., y / 2. + ys * 0.001, ys)
            glColor4f(*self.color)
            for x in xvals:
                glVertex3f(x, yvals[0], 0)
                glVertex3f(x, yvals[-1], 0)
            for y in yvals:
                glVertex3f(xvals[0], y, 0)
                glVertex3f(xvals[-1], y, 0)

            glEnd()

**Comment by ixjlyons** [comment]
Fixed by #648

**Comment by MeechaelA** [comment]
I think it would be beneficial to allow this attribute to be set by the user, of course with a default.

**Comment by ixjlyons** [comment]
It should be settable with `griditem.color = pg.glColor(...)`, though I think a `setColor` method should've been added to be more consistent with the rest of the library. There were/are several pull requests open to fix this and the one that got merged just used a regular attribute. One issue is that since the current version accepts only a tuple with values in the range [0, 1], it isn't feasible to accept that as well as anything you can pass to `glColor` (because we can't tell if, for example, `(1, 1, 1, 1)` is specified on the [0, 255] or [0, 1] scale). It would've been nice to offer `griditem.setColor('r')` or whatever else `mkColor` can accept, but now that breaks backwards compatibility. It's not too big of a deal as the user can always do `griditem.setColor(pg.glColor('r'))`. On the other hand, there hasn't been an official release since that pull request was merged, so maybe it's not really a backwards compatibility problem.

@flutefreak7 any thoughts?

**Comment by ixjlyons** [comment]
Update if interested: https://github.com/pyqtgraph/pyqtgraph/issues/283 has been merged
