### ISSUE TITLE
pg.PColorMeshItem crashes when x, y array shapes are changed (setData(x, y, z...)).

### ISSUE THREAD

**Issue by Ouam74** [pyqtgraph/pyqtgraph#2875]
I am creating a plot using the **PColorMeshItem** over time (i have a timer loop in pyside6), if i change the oversampling of my datas, then the x, y and z array shapes are changing and the python code generates an error when setting the data using the setData(x, y, z) function : 

Traceback (most recent call last):
  File "D:\3-Python_Programs\...\Radar_Olivier.py", line 203, in updatePlot
    self.img4.setData(x_vals, y_vals, np.flipud(np.abs(angle_arr.T)))
  File "D:\3-Python_Programs\...\venv\lib\site-packages\pyqtgraph\graphicsItems\PColorMeshItem.py", line 243, in setData
    if np.any(self.x != args[0]) or np.any(self.y != args[1]):
ValueError: operands could not be broadcast together with shapes (129,801) (65,401) 

I found the problem... 
In the "PColorMeshItem.py" file on the line **242** : 
replace:
      if np.any(self.x != args[0]) or np.any(self.y != args[1]): 
with : 
      **if np.any(self.x != args[0].shape[0]) or np.any(self.y != args[1].shape[1]):**

Then the problem is solved.
Thank you !

**Comment by pijyoi** [comment]
I think both branches below that are testing for "shape changed" are problematic in their own way:
https://github.com/pyqtgraph/pyqtgraph/blob/fa26ecef59be4a67164d0e27924fb65f4bb188bc/pyqtgraph/graphicsItems/PColorMeshItem.py#L228-L233

The 3-argument branch, which is the one concerned in this issue, could be fixed by using `functions.eq()`:
https://github.com/pyqtgraph/pyqtgraph/blob/fa26ecef59be4a67164d0e27924fb65f4bb188bc/pyqtgraph/functions.py#L642-L644

**Comment by pijyoi** [comment]
The existing "shapeChanged" logic was before "dataBounds" was implemented.
What is really wanted is to check if the data bounds have changed. i.e. "shapeChanged" is actually a misnomer.

```python
old_bounds = self._dataBounds
self._prepareData(args)
shapeChanged = old_bounds != self._dataBounds
```
