### ISSUE TITLE
Handles' positions can't be updated when the whole roi been dragged.

### ISSUE THREAD

**Issue by Chester-zZz** [pyqtgraph/pyqtgraph#294]
When the whole roi been dragged, the function roi.getLocalHandlePositions(index=i) can't return the newest positions of the handles.
I've tested it with the example "ROIExamples.py" installed with the pyqtgraph 0.9.10.
If the handle been dragged, the position can be updated. But if the whole roi been dragged, the positions of the handles stays the same.

I looked the code of ROI, but can't figure it out, hope it could be fixed.
Thanks.

**Comment by j9ac9k** [comment]
Hi @Chester-zZz 

Sorry for the really long delay before a follow up.  I just tested this out, and the index positions update as they are supposed to.  I briefly attempted to git bisect my way back; but 0.9.10 only worked with Qt4, which not only do we not support, but it's really tough to install.  I ran into some errors trying to run on 0.10.0 and 0.11.0 (which I'm sure we could have worked around), but as I can't replicate this issue any more, and given the number of changes we've made since this issue was opened, I feel confident saying this has been addressed. 

Thanks for reporting, and again, sorry it took us so long to follow up.
