### ISSUE TITLE
ImageItem shows an image as transposed

### ISSUE THREAD

**Issue by espdev** [pyqtgraph/pyqtgraph#315]
A simple example (uses image data from scikit-image):
```python
from pyqtgraph.Qt import QtCore, QtGui
import pyqtgraph as pg
from skimage import data

app = QtGui.QApplication([])

win = QtGui.QMainWindow()
win.resize(800, 800)
imv = pg.ImageView()
win.setCentralWidget(imv)
win.show()

imv.setImage(data.camera())

app.exec_()
```

Result:
<img width="300" alt="pg" src="https://cloud.githubusercontent.com/assets/1299189/14629248/f22d89ce-060d-11e6-8695-0c225f4ccc58.PNG">

**Comment by lesauxvi** [comment]
This is not an issue. This is the normal behaviour of the library regarding images...

**Comment by espdev** [comment]
@lesauxvi Why is this behaviour normal? Why have you done it like this? Where this is required? I do not know other programs/libraries that have this behaviour. For example, [matplotlib](http://matplotlib.org/users/image_tutorial.html), [matlab](http://www.mathworks.com/help/matlab/ref/image.html) and [opencv](http://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_gui/py_image_display/py_image_display.html) show images without transposing.

**Comment by lesauxvi** [comment]
I know, it is strange compared to othe libraries, and I do not know the reason behind this choice. May be @campagnola can give us some information ?

**Comment by campagnola** [comment]
It is a known issue. It is the one behavior I most regret that still exists in pyqtgraph for backward compatibility. For now, just use `imv.setImage(data.camera().T)`; this should actually improve performance as well.

I have been thinking about ways to deprecate this behavior slowly, something like:

1. *0.9.11* would have a config option to use normal image alignment instead of legacy
2. *0.9.12* would add a warning that default behavior will change, and users need to explicitly select normal or legacy to make the warning go away
3. *1.0* finally switch the default behavior.  

You will probably also find that the view needs to be flipped vertically as well (`imv.invertY()`); this is a known issue for which there may not be a good solution. Images have their y-axis pointing downward, whereas plots have their y-axis pointing upward by default. It is difficult to reconcile these without creating some counterintuitive behavior for someone else.
