### ISSUE TITLE
Wrong Log-axis?

### ISSUE THREAD

**Issue by erikthysell** [pyqtgraph/pyqtgraph#535]
I have a problem/error (I think) when trying to have the x-axis logarithmic
`self.qtplot.getPlotItem().setLogMode(True,None)`
where qtplot is a PlotWidget.
I get the error

> Continuum\Anaconda3\Lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py:764: RuntimeWarning: overflow encountered in power
>   return ["%0.1g"%x for x in 10 ** np.array(values).astype(float)]

as I use this (my x-axis goes from 0-10000)

It seems as if log-scale is the opposite of what it should be...
compare:
AxisItem.py:763
```
def logTickStrings(self, values, scale, spacing):
        return ["%0.1g"%x for x in 10 ** np.array(values).astype(float)]
```

I think this is the opposite of a logarithmic axis - this is a exponential axis...
shouldn't it be np.log10(....)

**Comment by chronologist89** [comment]
I think what happens is that the values are being transformed back and forth once for some computation reason. The axis values end up correct, but because of the first "power 10" transformation it easily overflows for large numbers (which is where you would usually use log-scale). So there has to be a way to achieve the same functionality while avoiding overruns.

**Comment by 2xB** [comment]
* If you set the x range from 0 to 10000 in log mode, it effectively sets it to a range from 10**0 to 10**10000, where the latter is a very large number. That is what your RuntimeWarning states.
 * The tick labels of log ticks in a logarithmic axis are exponential (10**0, 10**1, 10**2, ...)

**Comment by 2xB** [comment]
If you have further comments on this, feel free to leave one here or in a new issue!
