### ISSUE TITLE
Segfault on creation of new pg.TextItem from otherwise clear/empty console

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#536]
the following code generates a segfault

```python
import pyqtgraph as pg
label = pg.TextItem('text')
```

I'm running on Linux, using Python 3.6.2, PyQt5  (which uses Qt 5.6.2 underneath).  All packages installed via conda defaults channel.

I should note, I am able to generate textitems in my larger application; but while debugging another issue, I came across this.

I'm not really sure how to debug segmentation faults, so if there is some other information I could provide, let me know.

**Comment by j9ac9k** [comment]
same text on windows results in a different error:

```python
import pyqtgraph as pg
label = pg.TextItem('text')
Process finished with exit code -1073741819 (0xC0000005)
```

This is with python 3.6.2; with pyqtgraph (and PyQt5) installed via conda defaults channel

**Comment by j9ac9k** [comment]
Incrementing through the debugger, I got the segfault on this line of code inside TextItem.py:

```
self.textItem.setDefaultTextColor(self.color)
```

**Comment by j9ac9k** [comment]
I installed PyQt5.9 via pip, and got the same error.

Then I switched to PySide (in the conda-forge channel), ran the same code, and got the following message:

```
>>> import pyqtgraph as pg
>>> label = pg.TextItem('text')
QFont: Must construct a QApplication before a QFont
>>>
```

So I guess this is a PyQt5 bug?

**Comment by ixjlyons** [comment]
Not really a bug per se, since a lot of Qt objects require that a `QApplication` is set up first (basically everything in the `QtWidgets` module as far as I know). Notice in all of the example scripts up near the top there is something to create the application, such as `pg.mkQApp()`, `pg.plot()`, or `QtGui.QApplication([])`. Then at the end of the script you'll need to get the `QApplication` instance and call `exec_()` to start the Qt event loop and run the application. A fairly clean (i.e. no PyQt code) way to do this is:

```python
import pyqtgraph as pg
plot = pg.plot([1, 2, 3], [1, 3, 9])
label = pg.TextItem('text')
plot.addItem(label)
pg.mkQApp().exec_()
```

Here, the call to `pg.plot` creates the `QApplication` instance in the background for you, then `pg.mkQApp()` at the end just returns the current instance since it has been created already. A slightly more explicit example might be:

```python
import pyqtgraph as pg
app = pg.mkQApp()
plot = pg.plot([1, 2, 3], [1, 3, 9])
label = pg.TextItem('text')
plot.addItem(label)
app.exec_()
```

I notice that the documentation talks about command line usage and kind of ignores the event loop stuff. Establishing a clear convention with short examples in the docs and then using that convention in all of the example scripts would be good.

**Comment by j9ac9k** [comment]
As soon as I saw the pyside warning/error, I realized that not being in a qapplication would be problematic; suppose nothing here for pyqtgraph to address; therefore closing the issue.
