### ISSUE TITLE
Update conda packaging

### ISSUE THREAD

**Issue by DasVinch** [pyqtgraph/pyqtgraph#602]
conda install pyqtgraph still takes you to release 0.10.0 (master HEAD), which is 186 commits behind develop. Would it be possible to update the conda package/make it track develop ?

Best,

DasVinch

**Comment by flutefreak7** [comment]
You're asking him to make a release. He only releases once certain milestones have been met or there is a reasonable expectation of stability. Conda packages are not generally intended to reflect continuous integration of current development, but rather provide the latest release with known compatibility with certain versions of dependencies and various platforms.

Some packages are more up to date on the conda-forge channel since it is community maintained. Often pip gets updated before conda and pip can update directly from GitHub since that's what it sounds like you want to do. Note that this might be less stable since you would be installing pre-release code. Any bugs you find could be helpful though.

**Comment by j9ac9k** [comment]
Going to close this issue in part because we've been discussing this; we're working toward making another stable release right now.  You can read more about our current efforts here:

https://github.com/pyqtgraph/pyqtgraph/issues/822

If you would like to assist with getting the next version out, please take a look at any issues labeled `[CI-Fail]` and try and address those!
