### ISSUE TITLE
PEP-8

### ISSUE THREAD

**Issue by kamikaze** [pyqtgraph/pyqtgraph#612]
Please follow PEP-8

**Comment by campagnola** [comment]
Can you elaborate? We aim to follow a subset of PEP 8 but this is not strictly enforced, and there is still a lot of old code hanging around with more lax coding style. I generally clean code whenever I need to touch it for another reason.

If you're referring to the use of `camelCase` names, that decision was made in order to be consistent with Qt; it was just too messy mixing the two styles together in one package.
