### ISSUE TITLE
How to plot different plot type in plot area?

### ISSUE THREAD

**Issue by faststare** [pyqtgraph/pyqtgraph#632]
example candlestick with volume(bar chart) data. is it possible with pyqtgraph? what method I need to plot this? how about y-axis of this? they shared x-axis(datetime/timestamp) but they are not same y-axis data.

**Comment by j9ac9k** [comment]
@faststare sorry nobody has followed up here with you on this.  

Generally speaking, if you want overlapping plots with different y-axes, the best way to do that is to super-position viewboxes, where each viewbox contains one plot that want to use.  In order to do that, you will need to figure out what you want to do with your vertical axes.

I'm going to close out this issue, but I'll link you to an older project I did this for so hopefully the code will get you a basic idea:

https://github.com/j9ac9k/timeview/blob/master/timeview/gui/plot_area.py

Best of luck, let us know if you have other questions.
