### ISSUE TITLE
py2exe can not work with setWindowIcon rightly?

### ISSUE THREAD

**Issue by huoyunjie** [pyqtgraph/pyqtgraph#639]
I use win.setWindowIcon(QtGui.QIcon('../ico/main.ico')) in my program, PyCharm can work rightly. I can see then ico image in the application. After I use py2exe to build this program, the ico image disappeared. I had copied the ico dir and file rightly.
Can anyone help me?

**Comment by feketeimre** [comment]
This is not a pyqtgraph issue.

1. You need to look at the [distutils manual](https://docs.python.org/2/distutils/setupscript.html#installing-additional-files) and figure out how to bundle files.
2. When using Qt, you have to include imageformat codec dlls in order to load/save images through Qt.

This is how it would happen:
```python
...
data_files = [("ico", ["ico\icon.ico"])]
data_files.append(('imageformats',glob("C:\Python27\Lib\site-packages\PyQt4\plugins\imageformats\*.*"))) # or wherever you have these dlls
setup(options={...}, windows=[...], data_files=data_files)
```
