### ISSUE TITLE
Plot viewRect() returns swapped Y axis values

### ISSUE THREAD

**Issue by ekigwana** [pyqtgraph/pyqtgraph#708]
Given a plotWidget pw where: xmin = 0, xmax = 1, ymin = 0,  ymax = 1
```
view = pw.viewRect()
print 'l: %f\tr: %f\tb: %f\tt: %f' % (view.left(), view.right(), view.bottom(), view.top())
view = pw.viewRange()
print 'l: %f\tr: %f\tb: %f\tt: %f' % (view[0][0], view[0][1], view[1][0], view[1][1])
```
output is as follows:
```
l: 0 r: 1 b: 1 t: 0
l: 0 r: 1 b: 0 t: 1
```
I like the QRectF return because it is clear what's what for now I'll use viewRange so my code does not break when it is fixed.

**Comment by campagnola** [comment]
This is actually the expected behavior as defined by QRectF; for example:
```
>>> from PyQt5.QtCore import QRectF
>>> r = QRectF(0, 0, 1, 1)
>>> r.bottom()
1.0
>>> r.top()
0.0
```
The reason for this is that QRect was originally used to indicate regions of a widget, where the origin is at the top-left corner and the y-axis points downward. Later, QRectF was used in GraphicsView where you can't make any assumptions about the orientation of a rectangle relative to the view, so in that context, "bottom" really means "the edge with the highest y value", and not "the edge closest to the bottom of the screen".
