### ISSUE TITLE
ValueError: mmap length is greater than file size 

### ISSUE THREAD

**Issue by sachinsngh165** [pyqtgraph/pyqtgraph#730]
It's been many months since I'm using pyqtgraph and it's amazing. But recently when I've updated my maxOS to High Sierra 10.13.6 I'm facing following issue:
`ValueError: mmap length is greater than file size`
When I'm trying to run the pyqtgraph remote plotting example, the same is being thrown
Complete log is [here](https://gist.github.com/sachinsngh165/65df4e4f3dc81a283379dc032cf48220)
I'm using PyQt4+ python2.7
Also same error with PyQt5 + Python3
Please help me out it's urgent as I have to complete my project within a week.

**Comment by campagnola** [comment]
I don't have an OSX 10.13 system to test on, but you could try playing with the file size here:
https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/widgets/RemoteGraphicsView.py#L154
I would try replacing that line with something like:
```self.shmFile.write(b'\x00' * (4 * mmap.PAGESIZE + 1))```
just to see whether that is the source of the problem. It seems a bit unlikely, though, since the line that generates the error is also requesting `mmap.PAGESIZE` as the length to be mapped. Another thing I would try is just printing out mmap.PAGESIZE on both main process and subprocess to be sure they are the same (possibly the remote process is using a different python version?)

**Comment by sachinsngh165** [comment]
Thank you @campagnola, I would try your suggestions.

**Comment by campagnola** [comment]
Thanks @belinghy! PR should be merged soon.
