### ISSUE TITLE
addItem to a layout removes it from another layout

### ISSUE THREAD

**Issue by sahaskn** [pyqtgraph/pyqtgraph#746]
Adding a plotItem to a layout automatically removes it from another one. I'm just wondering whether this is default behaviour.

code:

```
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import pyqtgraph as pg

win = pg.GraphicsLayoutWidget(show=True, title="Basic plotting examples")
win.resize(1000,600)
win.setWindowTitle('pyqtgraph example: Plotting')

# Enable antialiasing for prettier plots
pg.setConfigOptions(antialias=True)

p1 = win.addPlot(title="Basic array plotting", y=np.random.normal(size=100))

p2 = win.addPlot(title="Multiple curves")
p2.plot(np.random.normal(size=100), pen=(255,0,0), name="Red curve")
p2.plot(np.random.normal(size=110)+5, pen=(0,255,0), name="Green curve")
p2.plot(np.random.normal(size=120)+10, pen=(0,0,255), name="Blue curve")

#============================
#Layout with only one item (to stretch over window)
mw = pg.GraphicsLayout()
cent = win.centralWidget

#adding plotItem to different layout
mw.addItem(p1) #this removes p1 from cent
win.setCentralWidget(mw)

#restoring back
win.setCentralWidget(cent)
```

**Comment by bradyzp** [comment]
This is expected behavior I believe, due to the way that Qt objects are owned.

The `PlotItem` (p1) is ultimately derived from [QGraphicsWidget](http://doc.qt.io/qt-5/qgraphicswidget.html) and a QWidget/QGraphicsWidget can only have a single parent/owner. When you add `p1` to your second GraphicsLayout `mw` the ownership is transferred, and it is removed from its original parent.

This documentation article goes into the basics of how Qt builds/maintains its object graph [Qt Object Trees & Ownership ](http://doc.qt.io/qt-5/objecttrees.html)

If what you're trying to do is create a second view of your plot `p1`, the easiest way would be to create another plot item via `win.addPlot`, and link it to the same data used by `p1`.

Take a look at the linkedViews.py example in the pyqtgraph/examples folder, it demonstrates basically what I described above, and also demonstrates the linking of the x/y axis's in various ways so that when you pan/zoom in one of your plots, the view changes are reflected in the linked views as well.

[Linked Views example](https://github.com/pyqtgraph/pyqtgraph/blob/develop/examples/linkedViews.py)

**Comment by sahaskn** [comment]
@bradyzp : Thanks a lot for beautifully explaining it.

**Comment by sem-geologist** [comment]
While I agree that PlotItem should be removed from parent when other parent is assigned (as it inherits from `QGraphicsWidget` class), however `PlotDataItem` inherits from  `pg.GraphicsObject` which ultimately inherits not from `QGraphicsWidget`, but from `pg.GraphicsItem` and `QGraphicsObject`, and such behaviour is unintuitive for someone who are used with Qt views and not widgets. The pyqtgraphs documentation is not very clear about the behaviour, ([http://pyqtgraph.org/documentation/plotting.html](http://pyqtgraph.org/documentation/plotting.html)) where it states that pyqtgraph it is based heavily on Qt’s GraphicsView framework, however, unfortunately it does not state clearly that pyqtgraph does not follow that framework. Qt’s GraphicsView framework tries to resemble the Qt Gui framework which uses the data-model-view paradigm, where you can feed your model into many views (e.g. QTreeView, QListView, QTableView...) simultaneously. In that sense, Qt’s GraphicsView framework uses the QGraphicsObject as "model", and QGraphicsWidgets as the "view". There is really nice example of Qt called "40000 Chips" ([http://doc.qt.io/qt-5/qtwidgets-graphicsview-chip-example.html](http://doc.qt.io/qt-5/qtwidgets-graphicsview-chip-example.html)), where 4 diferent views shows the exactly same QtGraphicsObjects.

In pyqtgraph this behaviour got broken by  `pg.GraphicsItem._updateView()`, which particularly checks and removes the item from previous view. I understand that this `GraphicsItem`class was a hack for all kind of dpi issues particularly present with Qt4, but I am not sure it is still is valid with PyQt5 and Pyside2?

**Comment by sahaskn** [comment]
@bradyzp and @sem-geologist : I found the case also for widgets that contains one plot in pyqtgraph. What I was trying to achieve is that I've a set of plots on grid layout by any means available in pyqtgraph and if I double click (or other means) a plot, then it gets expanded to the whole window for better view and when I double clicked it again, then it restores the original multiplots view with the changes that I will made on it when it's expanded to whole window. 
Right now, I'm thinking of algorithm that each plot remembers its index in grid so that the goal is achieved. This is a part of data analysis system as a part of my PhD work, I'm looking forward. 
Anyways, thanks a lot for your comments which are really useful.
