### ISSUE TITLE
Multiple Y Axes

### ISSUE THREAD

**Issue by hhprogram** [pyqtgraph/pyqtgraph#749]
Was the functionality to plot data of different units on 'left' and 'right' Y axies ever built into PlotItem? I don't think it was and I don't think the workaround will work if the added items don't respond to mouse interactions.

(workaround I'm referring to: http://bazaar.launchpad.net/~luke-campagnola/pyqtgraph/inp/view/head:/examples/MultiplePlotAxes.py)

**Comment by campagnola** [comment]
Can you provide a simple example that does not work the way you expect?

**Comment by 2xB** [comment]
In the example, you should be able to interact with the axes by hovering over the axes and then using your mouse buttons. Depending on the axis you are hovering, the corresponding axis is manipulated. It would be great if you could check if this works for you. If not, could you provide your PyQtGraph and Python Qt version and describe how it does not work? Or if I misunderstood your issue, it'd be great if you would explain again. Thank you!

If you have further questions or comments, feel free to leave them here or in a new issue. If I misunderstood you and this is not solved, I will of course reopen this issue!

PS: You are btw. referring to an official PyQtGraph example, which is also part of this repository: https://github.com/pyqtgraph/pyqtgraph/blob/develop/examples/MultiplePlotAxes.py

**Comment by j9ac9k** [comment]
@hhprogram I did this in an old project of mine, [TimeView](https://github.com/j9ac9k/timeview), the basic way I handled this was I overlayed viewboxes, where each viewbox contained one plot/y-axis I wanted to include.

It's been a while since I worked on that project, but here is the call I make when adding an extra "view" to my plot area:

https://github.com/j9ac9k/timeview/blob/master/timeview/gui/plot_area.py#L170-L198

**Comment by 0000matteo0000** [comment]
i implemented a multi axis widget #1359
