### ISSUE TITLE
Legend fail with QGraphicsEllipseItem

### ISSUE THREAD

**Issue by matthieuberger** [pyqtgraph/pyqtgraph#766]
Hi,

I'm trying to set up a pie chart with a legend. Unfortunately, the LegendItem object is looking for an 'opts' attribute wich is not present in the QtGui.QGraphicsEllipseItem object.
It return the following traceback:
`AttributeError: 'PySide.QtGui.QGraphicsEllipseItem' object has no attribute 'opts'
Traceback (most recent call last):
  File "/lib/python2.7/site-packages/pyqtgraph/graphicsItems/LegendItem.py", line 149, in paint
    opts = self.item.opts`

**Comment by NilsNemitz** [comment]
Dear @matthieuberger, 

If you are still working on this, can you maybe give us some more detail on what you have set up?
I am pretty sure that your issue is that LegendItem expects a know PyQtGraph plot item, typically a PlotDataItem, in its `addItem()` call. 

https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/legenditem.html

It then extracts the suitable symbol from the internal `opts` dictionary of that item. It looks like you are passing the QGraphicsEllipse object you use to draw the pie chart. And that indeed does not have an `opts` dictionary, or the desired information in it.

Setting custom symbols independent of a plot is not directly supported by the curent LegendItem. However, `addItem()` will accept a `SampleItem` as defined in pyqtgraph/graphicsItems/LegendItem.py:
`class ItemSample(GraphicsWidget):`

You can create a subclass of this to draw whatever you need to be drawn by overriding the `paint()` method. (And maybe the `mouseClickEvent()` if you don't want to bother with the visible / invisible toggle.)

Hope this helps you or somebody else...

**Comment by j9ac9k** [comment]
Hi @matthieuberger 

I'm going to close out this issue, as I'm not sure we have much we can do here. 

If this is a persistent issue, feel free to post here or open a new issue, if you provide some source code or better yet, a minimum working example, we can be better prepared to help you.  Sorry for the long delay in response!
